-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln152 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln144 : IN STD_LOGIC_VECTOR (14 downto 0);
    add_ln144 : IN STD_LOGIC_VECTOR (1 downto 0);
    sext_ln152 : IN STD_LOGIC_VECTOR (31 downto 0);
    move_type_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    move_type_1_out_ap_vld : OUT STD_LOGIC;
    row2_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    row2_1_out_ap_vld : OUT STD_LOGIC;
    M_e_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_0_ce0 : OUT STD_LOGIC;
    M_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_1_ce0 : OUT STD_LOGIC;
    M_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_2_ce0 : OUT STD_LOGIC;
    M_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_3_ce0 : OUT STD_LOGIC;
    M_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv34_3FFFFFFFF : STD_LOGIC_VECTOR (33 downto 0) := "1111111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_cond44_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln155_fu_248_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln155_reg_381 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln152_fu_252_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln152_reg_386 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln152_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln152_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln154_fu_240_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal move_type_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal move_type_3_fu_299_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal row2_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal row2_3_fu_308_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_84 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal zext_ln152_cast_fu_182_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_sig_allocacmp_r_1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal M_e_0_ce0_local : STD_LOGIC;
    signal M_e_1_ce0_local : STD_LOGIC;
    signal M_e_2_ce0_local : STD_LOGIC;
    signal M_e_3_ce0_local : STD_LOGIC;
    signal trunc_ln154_fu_204_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln154_1_fu_216_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_208_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl4_fu_220_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln154_1_fu_228_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln154_fu_234_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln152_cast_fu_178_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal v_fu_270_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_fu_270_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln155_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal v_fu_270_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_fu_270_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_fu_270_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal v_fu_270_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component fmm_reduce_kernel_sparsemux_9_2_32_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_x_U71 : component fmm_reduce_kernel_sparsemux_9_2_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 32,
        CASE1 => "10",
        din1_WIDTH => 32,
        CASE2 => "11",
        din2_WIDTH => 32,
        CASE3 => "00",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => M_e_0_q0,
        din1 => M_e_1_q0,
        din2 => M_e_2_q0,
        din3 => M_e_3_q0,
        def => v_fu_270_p9,
        sel => add_ln144,
        dout => v_fu_270_p11);

    flow_control_loop_pipe_sequential_init_U : component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    move_type_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    move_type_fu_76 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    move_type_fu_76 <= move_type_3_fu_299_p3;
                end if;
            end if; 
        end if;
    end process;

    r_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_84 <= zext_ln152_cast_fu_182_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    r_fu_84 <= add_ln152_reg_386;
                end if;
            end if; 
        end if;
    end process;

    row2_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    row2_fu_80 <= ap_const_lv32_FFFFFFFF;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    row2_fu_80 <= row2_3_fu_308_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln152_reg_386 <= add_ln152_fu_252_p2;
                icmp_ln152_reg_391 <= icmp_ln152_fu_258_p2;
                trunc_ln155_reg_381 <= trunc_ln155_fu_248_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    M_e_0_address0 <= zext_ln154_fu_240_p1(15 - 1 downto 0);
    M_e_0_ce0 <= M_e_0_ce0_local;

    M_e_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_0_ce0_local <= ap_const_logic_1;
        else 
            M_e_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_1_address0 <= zext_ln154_fu_240_p1(15 - 1 downto 0);
    M_e_1_ce0 <= M_e_1_ce0_local;

    M_e_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_1_ce0_local <= ap_const_logic_1;
        else 
            M_e_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_2_address0 <= zext_ln154_fu_240_p1(15 - 1 downto 0);
    M_e_2_ce0 <= M_e_2_ce0_local;

    M_e_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_2_ce0_local <= ap_const_logic_1;
        else 
            M_e_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_3_address0 <= zext_ln154_fu_240_p1(15 - 1 downto 0);
    M_e_3_ce0 <= M_e_3_ce0_local;

    M_e_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_3_ce0_local <= ap_const_logic_1;
        else 
            M_e_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln152_fu_252_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_1) + unsigned(ap_const_lv34_3FFFFFFFF));
    add_ln154_1_fu_228_p2 <= std_logic_vector(unsigned(p_shl_fu_208_p3) + unsigned(p_shl4_fu_220_p3));
    add_ln154_fu_234_p2 <= std_logic_vector(unsigned(add_ln154_1_fu_228_p2) + unsigned(zext_ln144));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, or_cond44_fu_316_p2)
    begin
        if (((or_cond44_fu_316_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_r_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, add_ln152_reg_386, ap_block_pp0_stage0, ap_loop_init, r_fu_84, zext_ln152_cast_fu_182_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_r_1 <= zext_ln152_cast_fu_182_p1;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_r_1 <= add_ln152_reg_386;
            else 
                ap_sig_allocacmp_r_1 <= r_fu_84;
            end if;
        else 
            ap_sig_allocacmp_r_1 <= r_fu_84;
        end if; 
    end process;

    icmp_ln152_fu_258_p2 <= "1" when (signed(add_ln152_fu_252_p2) > signed(sext_ln152_cast_fu_178_p1)) else "0";
    icmp_ln155_fu_293_p2 <= "1" when (v_fu_270_p11 = ap_const_lv32_0) else "0";
    move_type_1_out <= 
        move_type_fu_76 when (icmp_ln155_fu_293_p2(0) = '1') else 
        v_fu_270_p11;

    move_type_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_cond44_fu_316_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (or_cond44_fu_316_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            move_type_1_out_ap_vld <= ap_const_logic_1;
        else 
            move_type_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    move_type_3_fu_299_p3 <= 
        move_type_fu_76 when (icmp_ln155_fu_293_p2(0) = '1') else 
        v_fu_270_p11;
    or_cond44_fu_316_p2 <= (icmp_ln155_fu_293_p2 and icmp_ln152_reg_391);
    p_shl4_fu_220_p3 <= (trunc_ln154_1_fu_216_p1 & ap_const_lv4_0);
    p_shl_fu_208_p3 <= (trunc_ln154_fu_204_p1 & ap_const_lv6_0);
    row2_1_out <= 
        row2_fu_80 when (icmp_ln155_fu_293_p2(0) = '1') else 
        trunc_ln155_reg_381;

    row2_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_cond44_fu_316_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (or_cond44_fu_316_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row2_1_out_ap_vld <= ap_const_logic_1;
        else 
            row2_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    row2_3_fu_308_p3 <= 
        row2_fu_80 when (icmp_ln155_fu_293_p2(0) = '1') else 
        trunc_ln155_reg_381;
        sext_ln152_cast_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln152),34));

    trunc_ln154_1_fu_216_p1 <= ap_sig_allocacmp_r_1(11 - 1 downto 0);
    trunc_ln154_fu_204_p1 <= ap_sig_allocacmp_r_1(9 - 1 downto 0);
    trunc_ln155_fu_248_p1 <= ap_sig_allocacmp_r_1(32 - 1 downto 0);
    v_fu_270_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    zext_ln152_cast_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln152),34));
    zext_ln154_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln154_fu_234_p2),64));
end behav;
