-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    new_col : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln121 : IN STD_LOGIC_VECTOR (14 downto 0);
    mul_ln122 : IN STD_LOGIC_VECTOR (14 downto 0);
    mul_ln133 : IN STD_LOGIC_VECTOR (14 downto 0);
    icmp_ln196 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp34_i : IN STD_LOGIC_VECTOR (0 downto 0);
    M_e_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_0_ce0 : OUT STD_LOGIC;
    M_e_0_we0 : OUT STD_LOGIC;
    M_e_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_1_ce0 : OUT STD_LOGIC;
    M_e_1_we0 : OUT STD_LOGIC;
    M_e_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_2_ce0 : OUT STD_LOGIC;
    M_e_2_we0 : OUT STD_LOGIC;
    M_e_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_3_ce0 : OUT STD_LOGIC;
    M_e_3_we0 : OUT STD_LOGIC;
    M_e_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln124_reg_439 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_4_reg_433 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln124_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal M_e_0_addr_reg_443 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln128_fu_276_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln128_reg_448 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln133_fu_282_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln133_reg_453 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln133_reg_453_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_1_addr_reg_458 : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_2_addr_reg_463 : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_3_addr_reg_468 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln124_fu_293_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln124_reg_473 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal M_e_0_addr_6_reg_479 : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_1_addr_6_reg_484 : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_2_addr_6_reg_489 : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_3_addr_6_reg_494 : STD_LOGIC_VECTOR (14 downto 0);
    signal e1_fu_303_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal e1_reg_499 : STD_LOGIC_VECTOR (31 downto 0);
    signal e1_reg_499_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln127_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln127_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal e2_fu_338_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal e2_reg_513 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln129_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln129_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln130_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln130_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln130_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln130_reg_526 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln130_2_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln130_2_reg_530 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal zext_ln126_fu_268_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln128_fu_296_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln133_fu_409_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal c_fu_74 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln124_fu_288_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_4 : STD_LOGIC_VECTOR (30 downto 0);
    signal M_e_0_ce0_local : STD_LOGIC;
    signal M_e_0_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_0_we0_local : STD_LOGIC;
    signal M_e_0_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_predicate_pred283_state8 : BOOLEAN;
    signal M_e_1_ce0_local : STD_LOGIC;
    signal M_e_1_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_1_we0_local : STD_LOGIC;
    signal M_e_1_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_pred311_state8 : BOOLEAN;
    signal M_e_2_ce0_local : STD_LOGIC;
    signal M_e_2_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_2_we0_local : STD_LOGIC;
    signal M_e_2_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_pred338_state8 : BOOLEAN;
    signal M_e_3_ce0_local : STD_LOGIC;
    signal M_e_3_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal M_e_3_we0_local : STD_LOGIC;
    signal M_e_3_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_pred365_state8 : BOOLEAN;
    signal zext_ln124_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln3_fu_252_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln126_fu_262_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal e1_fu_303_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal e1_fu_303_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal e2_fu_338_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln130_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln130_fu_382_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln130_2_fu_391_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln130_fu_385_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal e1_fu_303_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal e1_fu_303_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal e1_fu_303_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal e1_fu_303_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal e2_fu_338_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal e2_fu_338_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal e2_fu_338_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal e2_fu_338_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component fmm_reduce_kernel_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_U45 : component fmm_reduce_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => M_e_0_q0,
        din1 => M_e_1_q0,
        din2 => M_e_2_q0,
        din3 => M_e_3_q0,
        def => e1_fu_303_p9,
        sel => e1_fu_303_p10,
        dout => e1_fu_303_p11);

    sparsemux_9_2_32_1_1_U46 : component fmm_reduce_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => M_e_0_q0,
        din1 => M_e_1_q0,
        din2 => M_e_2_q0,
        din3 => M_e_3_q0,
        def => e2_fu_338_p9,
        sel => trunc_ln124_reg_473,
        dout => e2_fu_338_p11);

    flow_control_loop_pipe_sequential_init_U : component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                c_fu_74 <= ap_const_lv31_0;
            elsif (((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                c_fu_74 <= add_ln124_fu_288_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                M_e_0_addr_6_reg_479 <= zext_ln128_fu_296_p1(15 - 1 downto 0);
                M_e_1_addr_6_reg_484 <= zext_ln128_fu_296_p1(15 - 1 downto 0);
                M_e_2_addr_6_reg_489 <= zext_ln128_fu_296_p1(15 - 1 downto 0);
                M_e_3_addr_6_reg_494 <= zext_ln128_fu_296_p1(15 - 1 downto 0);
                    ap_predicate_pred283_state8 <= (((icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_0)) or ((ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_0)));
                    ap_predicate_pred311_state8 <= (((icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_1)) or ((ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_1)));
                    ap_predicate_pred338_state8 <= (((icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_2)) or ((ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_2)));
                    ap_predicate_pred365_state8 <= (((icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_3)) or ((ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_3)));
                e1_reg_499 <= e1_fu_303_p11;
                e1_reg_499_pp0_iter1_reg <= e1_reg_499;
                icmp_ln127_reg_509 <= icmp_ln127_fu_327_p2;
                trunc_ln124_reg_473 <= trunc_ln124_fu_293_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                M_e_0_addr_reg_443 <= zext_ln126_fu_268_p1(15 - 1 downto 0);
                M_e_1_addr_reg_458 <= zext_ln126_fu_268_p1(15 - 1 downto 0);
                M_e_2_addr_reg_463 <= zext_ln126_fu_268_p1(15 - 1 downto 0);
                M_e_3_addr_reg_468 <= zext_ln126_fu_268_p1(15 - 1 downto 0);
                add_ln128_reg_448 <= add_ln128_fu_276_p2;
                add_ln133_reg_453 <= add_ln133_fu_282_p2;
                add_ln133_reg_453_pp0_iter1_reg <= add_ln133_reg_453;
                c_4_reg_433 <= ap_sig_allocacmp_c_4;
                icmp_ln124_reg_439 <= icmp_ln124_fu_246_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                and_ln130_reg_522 <= and_ln130_fu_372_p2;
                e2_reg_513 <= e2_fu_338_p11;
                icmp_ln129_reg_518 <= icmp_ln129_fu_361_p2;
                or_ln130_reg_526 <= or_ln130_fu_377_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                icmp_ln130_2_reg_530 <= icmp_ln130_2_fu_394_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    M_e_0_address0 <= M_e_0_address0_local;

    M_e_0_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, M_e_0_addr_reg_443, ap_CS_fsm_pp0_stage1, M_e_0_addr_6_reg_479, ap_CS_fsm_pp0_stage3, zext_ln126_fu_268_p1, ap_block_pp0_stage0, zext_ln128_fu_296_p1, ap_block_pp0_stage1, zext_ln133_fu_409_p1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_0_address0_local <= zext_ln133_fu_409_p1(15 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            M_e_0_address0_local <= M_e_0_addr_6_reg_479;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            M_e_0_address0_local <= M_e_0_addr_reg_443;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            M_e_0_address0_local <= zext_ln128_fu_296_p1(15 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_0_address0_local <= zext_ln126_fu_268_p1(15 - 1 downto 0);
        else 
            M_e_0_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_0_ce0 <= M_e_0_ce0_local;

    M_e_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            M_e_0_ce0_local <= ap_const_logic_1;
        else 
            M_e_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_0_d0 <= M_e_0_d0_local;

    M_e_0_d0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, e1_reg_499_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_0_d0_local <= e1_reg_499_pp0_iter1_reg;
        elsif ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            M_e_0_d0_local <= ap_const_lv32_0;
        else 
            M_e_0_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_0_we0 <= M_e_0_we0_local;

    M_e_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln124_reg_439, ap_CS_fsm_pp0_stage4, trunc_ln124_reg_473, icmp_ln127_reg_509, ap_block_pp0_stage2_11001, icmp_ln129_reg_518, and_ln130_reg_522, or_ln130_reg_526, icmp_ln130_2_fu_394_p2, icmp_ln130_2_reg_530, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_predicate_pred283_state8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_0)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_0)))) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_fu_394_p2 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) 
    and (trunc_ln124_reg_473 = ap_const_lv2_0)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_0)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_pred283_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            M_e_0_we0_local <= ap_const_logic_1;
        else 
            M_e_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_1_address0 <= M_e_1_address0_local;

    M_e_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, M_e_1_addr_reg_458, ap_CS_fsm_pp0_stage1, M_e_1_addr_6_reg_484, ap_CS_fsm_pp0_stage3, zext_ln126_fu_268_p1, ap_block_pp0_stage0, zext_ln128_fu_296_p1, ap_block_pp0_stage1, zext_ln133_fu_409_p1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_1_address0_local <= zext_ln133_fu_409_p1(15 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            M_e_1_address0_local <= M_e_1_addr_6_reg_484;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            M_e_1_address0_local <= M_e_1_addr_reg_458;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            M_e_1_address0_local <= zext_ln128_fu_296_p1(15 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_1_address0_local <= zext_ln126_fu_268_p1(15 - 1 downto 0);
        else 
            M_e_1_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_1_ce0 <= M_e_1_ce0_local;

    M_e_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            M_e_1_ce0_local <= ap_const_logic_1;
        else 
            M_e_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_1_d0 <= M_e_1_d0_local;

    M_e_1_d0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, e1_reg_499_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_1_d0_local <= e1_reg_499_pp0_iter1_reg;
        elsif ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            M_e_1_d0_local <= ap_const_lv32_0;
        else 
            M_e_1_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_1_we0 <= M_e_1_we0_local;

    M_e_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln124_reg_439, ap_CS_fsm_pp0_stage4, trunc_ln124_reg_473, icmp_ln127_reg_509, ap_block_pp0_stage2_11001, icmp_ln129_reg_518, and_ln130_reg_522, or_ln130_reg_526, icmp_ln130_2_fu_394_p2, icmp_ln130_2_reg_530, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_predicate_pred311_state8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_1)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_1)))) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_fu_394_p2 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) 
    and (trunc_ln124_reg_473 = ap_const_lv2_1)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_pred311_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            M_e_1_we0_local <= ap_const_logic_1;
        else 
            M_e_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_2_address0 <= M_e_2_address0_local;

    M_e_2_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, M_e_2_addr_reg_463, ap_CS_fsm_pp0_stage1, M_e_2_addr_6_reg_489, ap_CS_fsm_pp0_stage3, zext_ln126_fu_268_p1, ap_block_pp0_stage0, zext_ln128_fu_296_p1, ap_block_pp0_stage1, zext_ln133_fu_409_p1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_2_address0_local <= zext_ln133_fu_409_p1(15 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            M_e_2_address0_local <= M_e_2_addr_6_reg_489;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            M_e_2_address0_local <= M_e_2_addr_reg_463;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            M_e_2_address0_local <= zext_ln128_fu_296_p1(15 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_2_address0_local <= zext_ln126_fu_268_p1(15 - 1 downto 0);
        else 
            M_e_2_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_2_ce0 <= M_e_2_ce0_local;

    M_e_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            M_e_2_ce0_local <= ap_const_logic_1;
        else 
            M_e_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_2_d0 <= M_e_2_d0_local;

    M_e_2_d0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, e1_reg_499_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_2_d0_local <= e1_reg_499_pp0_iter1_reg;
        elsif ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            M_e_2_d0_local <= ap_const_lv32_0;
        else 
            M_e_2_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_2_we0 <= M_e_2_we0_local;

    M_e_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln124_reg_439, ap_CS_fsm_pp0_stage4, trunc_ln124_reg_473, icmp_ln127_reg_509, ap_block_pp0_stage2_11001, icmp_ln129_reg_518, and_ln130_reg_522, or_ln130_reg_526, icmp_ln130_2_fu_394_p2, icmp_ln130_2_reg_530, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_predicate_pred338_state8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_2)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_2)))) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_fu_394_p2 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) 
    and (trunc_ln124_reg_473 = ap_const_lv2_2)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_2)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_pred338_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            M_e_2_we0_local <= ap_const_logic_1;
        else 
            M_e_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_3_address0 <= M_e_3_address0_local;

    M_e_3_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, M_e_3_addr_reg_468, ap_CS_fsm_pp0_stage1, M_e_3_addr_6_reg_494, ap_CS_fsm_pp0_stage3, zext_ln126_fu_268_p1, ap_block_pp0_stage0, zext_ln128_fu_296_p1, ap_block_pp0_stage1, zext_ln133_fu_409_p1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_3_address0_local <= zext_ln133_fu_409_p1(15 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            M_e_3_address0_local <= M_e_3_addr_6_reg_494;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            M_e_3_address0_local <= M_e_3_addr_reg_468;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            M_e_3_address0_local <= zext_ln128_fu_296_p1(15 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_3_address0_local <= zext_ln126_fu_268_p1(15 - 1 downto 0);
        else 
            M_e_3_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_3_ce0 <= M_e_3_ce0_local;

    M_e_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            M_e_3_ce0_local <= ap_const_logic_1;
        else 
            M_e_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_3_d0 <= M_e_3_d0_local;

    M_e_3_d0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, e1_reg_499_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_3_d0_local <= e1_reg_499_pp0_iter1_reg;
        elsif ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            M_e_3_d0_local <= ap_const_lv32_0;
        else 
            M_e_3_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_3_we0 <= M_e_3_we0_local;

    M_e_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln124_reg_439, ap_CS_fsm_pp0_stage4, trunc_ln124_reg_473, icmp_ln127_reg_509, ap_block_pp0_stage2_11001, icmp_ln129_reg_518, and_ln130_reg_522, or_ln130_reg_526, icmp_ln130_2_fu_394_p2, icmp_ln130_2_reg_530, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_predicate_pred365_state8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_reg_530 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_3)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_3)))) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (((icmp_ln124_reg_439 = ap_const_lv1_1) and (icmp_ln130_2_fu_394_p2 = ap_const_lv1_1) and (or_ln130_reg_526 = ap_const_lv1_0) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) 
    and (trunc_ln124_reg_473 = ap_const_lv2_3)) or ((icmp_ln124_reg_439 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln130_reg_522) and (or_ln130_reg_526 = ap_const_lv1_1) and (icmp_ln129_reg_518 = ap_const_lv1_0) and (icmp_ln127_reg_509 = ap_const_lv1_0) and (trunc_ln124_reg_473 = ap_const_lv2_3)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_pred365_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            M_e_3_we0_local <= ap_const_logic_1;
        else 
            M_e_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln124_fu_288_p2 <= std_logic_vector(unsigned(c_4_reg_433) + unsigned(ap_const_lv31_1));
    add_ln126_fu_262_p2 <= std_logic_vector(unsigned(mul_ln121) + unsigned(lshr_ln3_fu_252_p4));
    add_ln128_fu_276_p2 <= std_logic_vector(unsigned(mul_ln122) + unsigned(lshr_ln3_fu_252_p4));
    add_ln133_fu_282_p2 <= std_logic_vector(unsigned(mul_ln133) + unsigned(lshr_ln3_fu_252_p4));
    and_ln130_fu_372_p2 <= (icmp_ln196 and icmp_ln130_fu_367_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln124_reg_439)
    begin
        if (((icmp_ln124_reg_439 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_74, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_4 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_c_4 <= c_fu_74;
        end if; 
    end process;

    e1_fu_303_p10 <= c_4_reg_433(2 - 1 downto 0);
    e1_fu_303_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    e2_fu_338_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    icmp_ln124_fu_246_p2 <= "1" when (signed(zext_ln124_fu_242_p1) < signed(new_col)) else "0";
    icmp_ln127_fu_327_p2 <= "1" when (e1_fu_303_p11 = ap_const_lv32_0) else "0";
    icmp_ln129_fu_361_p2 <= "1" when (e2_fu_338_p11 = ap_const_lv32_0) else "0";
    icmp_ln130_2_fu_394_p2 <= "1" when (sext_ln130_2_fu_391_p1 = sub_ln130_fu_385_p2) else "0";
    icmp_ln130_fu_367_p2 <= "1" when (e1_reg_499 = e2_fu_338_p11) else "0";
    lshr_ln3_fu_252_p4 <= ap_sig_allocacmp_c_4(16 downto 2);
    or_ln130_fu_377_p2 <= (cmp34_i or and_ln130_fu_372_p2);
        sext_ln130_2_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(e1_reg_499),33));

        sext_ln130_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(e2_reg_513),33));

    sub_ln130_fu_385_p2 <= std_logic_vector(unsigned(ap_const_lv33_0) - unsigned(sext_ln130_fu_382_p1));
    trunc_ln124_fu_293_p1 <= c_4_reg_433(2 - 1 downto 0);
    zext_ln124_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_c_4),32));
    zext_ln126_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln126_fu_262_p2),64));
    zext_ln128_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln128_reg_448),64));
    zext_ln133_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_reg_453_pp0_iter1_reg),64));
end behav;
