-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_111 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    total_rows_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln267 : IN STD_LOGIC_VECTOR (61 downto 0);
    M_e_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    M_e_ce0 : OUT STD_LOGIC;
    M_e_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    s_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_3_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_111 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln104_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln93_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_reg_372_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_reg_379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_reg_379_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln95_2_fu_187_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln95_2_reg_383 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln95_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal cnt_fu_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal cnt_2_fu_309_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_2_fu_50 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln93_fu_191_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal s_2_fu_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln104_3_fu_290_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_12_fu_58 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln104_2_fu_216_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten30_fu_62 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln104_fu_143_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal s_10_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal M_e_ce0_local : STD_LOGIC;
    signal zext_ln93_fu_129_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln104_fu_149_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln95_fu_157_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln95_1_fu_169_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_shl_fu_161_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_shl8_fu_173_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln95_fu_181_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln104_1_fu_210_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln93_1_fu_223_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln95_2_fu_227_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln93_fu_248_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln107_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln107_fu_258_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln107_fu_264_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln107_fu_272_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln104_1_fu_283_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln95_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln95_1_fu_303_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    c_12_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    c_12_fu_58 <= ap_const_lv31_0;
                elsif (((icmp_ln104_reg_379 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    c_12_fu_58 <= select_ln104_2_fu_216_p3;
                end if;
            end if; 
        end if;
    end process;

    cnt_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    cnt_fu_46 <= ap_const_lv32_0;
                elsif (((icmp_ln104_reg_379_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    cnt_fu_46 <= cnt_2_fu_309_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten30_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten30_fu_62 <= ap_const_lv62_0;
                elsif (((icmp_ln104_fu_138_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten30_fu_62 <= add_ln104_fu_143_p2;
                end if;
            end if; 
        end if;
    end process;

    r_2_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_2_fu_50 <= ap_const_lv31_0;
                elsif (((icmp_ln104_fu_138_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    r_2_fu_50 <= add_ln93_fu_191_p2;
                end if;
            end if; 
        end if;
    end process;

    s_2_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    s_2_fu_54 <= ap_const_lv32_0;
                elsif (((icmp_ln104_reg_379_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    s_2_fu_54 <= select_ln104_3_fu_290_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln104_reg_379 <= icmp_ln104_fu_138_p2;
                icmp_ln93_reg_372 <= icmp_ln93_fu_133_p2;
                    trunc_ln95_2_reg_383(16 downto 6) <= trunc_ln95_2_fu_187_p1(16 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln104_reg_379_pp0_iter2_reg <= icmp_ln104_reg_379;
                icmp_ln93_reg_372_pp0_iter2_reg <= icmp_ln93_reg_372;
            end if;
        end if;
    end process;
    trunc_ln95_2_reg_383(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    M_e_address0 <= zext_ln95_fu_232_p1(17 - 1 downto 0);
    M_e_ce0 <= M_e_ce0_local;

    M_e_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            M_e_ce0_local <= ap_const_logic_1;
        else 
            M_e_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln104_1_fu_210_p2 <= std_logic_vector(unsigned(c_12_fu_58) + unsigned(ap_const_lv31_1));
    add_ln104_fu_143_p2 <= std_logic_vector(unsigned(indvar_flatten30_fu_62) + unsigned(ap_const_lv62_1));
    add_ln107_fu_258_p2 <= std_logic_vector(unsigned(trunc_ln93_fu_248_p1) + unsigned(ap_const_lv31_7FFFFFFF));
    add_ln93_fu_191_p2 <= std_logic_vector(unsigned(select_ln104_fu_149_p3) + unsigned(ap_const_lv31_1));
    add_ln95_1_fu_303_p2 <= std_logic_vector(unsigned(select_ln104_1_fu_283_p3) + unsigned(ap_const_lv32_1));
    add_ln95_2_fu_227_p2 <= std_logic_vector(unsigned(trunc_ln95_2_reg_383) + unsigned(trunc_ln93_1_fu_223_p1));
    add_ln95_fu_181_p2 <= std_logic_vector(unsigned(p_shl_fu_161_p3) + unsigned(p_shl8_fu_173_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln104_fu_138_p2)
    begin
        if (((icmp_ln104_fu_138_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cnt_2_fu_309_p3 <= 
        add_ln95_1_fu_303_p2 when (icmp_ln95_fu_297_p2(0) = '1') else 
        select_ln104_1_fu_283_p3;
    icmp_ln104_fu_138_p2 <= "1" when (indvar_flatten30_fu_62 = mul_ln267) else "0";
    icmp_ln107_fu_252_p2 <= "1" when (signed(cnt_fu_46) > signed(ap_const_lv32_0)) else "0";
    icmp_ln93_fu_133_p2 <= "1" when (signed(zext_ln93_fu_129_p1) < signed(total_rows_1)) else "0";
    icmp_ln95_fu_297_p2 <= "0" when (M_e_q0 = ap_const_lv32_0) else "1";
    p_shl8_fu_173_p3 <= (trunc_ln95_1_fu_169_p1 & ap_const_lv6_0);
    p_shl_fu_161_p3 <= (trunc_ln95_fu_157_p1 & ap_const_lv8_0);
    s_10_fu_276_p2 <= std_logic_vector(unsigned(zext_ln107_fu_272_p1) + unsigned(s_2_fu_54));
    s_3_out <= s_10_fu_276_p2;

    s_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln104_reg_379_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((icmp_ln104_reg_379_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            s_3_out_ap_vld <= ap_const_logic_1;
        else 
            s_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln104_1_fu_283_p3 <= 
        cnt_fu_46 when (icmp_ln93_reg_372_pp0_iter2_reg(0) = '1') else 
        ap_const_lv32_0;
    select_ln104_2_fu_216_p3 <= 
        c_12_fu_58 when (icmp_ln93_reg_372(0) = '1') else 
        add_ln104_1_fu_210_p2;
    select_ln104_3_fu_290_p3 <= 
        s_2_fu_54 when (icmp_ln93_reg_372_pp0_iter2_reg(0) = '1') else 
        s_10_fu_276_p2;
    select_ln104_fu_149_p3 <= 
        r_2_fu_50 when (icmp_ln93_fu_133_p2(0) = '1') else 
        ap_const_lv31_0;
    select_ln107_fu_264_p3 <= 
        add_ln107_fu_258_p2 when (icmp_ln107_fu_252_p2(0) = '1') else 
        ap_const_lv31_0;
    trunc_ln93_1_fu_223_p1 <= select_ln104_2_fu_216_p3(17 - 1 downto 0);
    trunc_ln93_fu_248_p1 <= cnt_fu_46(31 - 1 downto 0);
    trunc_ln95_1_fu_169_p1 <= select_ln104_fu_149_p3(29 - 1 downto 0);
    trunc_ln95_2_fu_187_p1 <= add_ln95_fu_181_p2(17 - 1 downto 0);
    trunc_ln95_fu_157_p1 <= select_ln104_fu_149_p3(27 - 1 downto 0);
    zext_ln107_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln107_fu_264_p3),32));
    zext_ln93_fu_129_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_2_fu_50),32));
    zext_ln95_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_2_fu_227_p2),64));
end behav;
