// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cols,
        bound,
        A_dram,
        A_dram_ap_vld,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_q0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_q0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_q0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] cols;
input  [61:0] bound;
output  [31:0] A_dram;
output   A_dram_ap_vld;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
input  [31:0] M_e_0_q0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
input  [31:0] M_e_1_q0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
input  [31:0] M_e_2_q0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
input  [31:0] M_e_3_q0;

reg ap_idle;
reg A_dram_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln68_fu_181_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] cmp4123_fu_157_p2;
reg   [0:0] cmp4123_reg_363;
reg   [0:0] icmp_ln68_reg_367;
wire   [1:0] trunc_ln69_fu_256_p1;
reg   [1:0] trunc_ln69_reg_371;
reg   [1:0] trunc_ln69_reg_371_pp0_iter3_reg;
wire   [14:0] add_ln71_fu_270_p2;
reg   [14:0] add_ln71_reg_376;
wire   [30:0] add_ln69_fu_276_p2;
reg   [30:0] add_ln69_reg_381;
wire   [0:0] icmp_ln69_1_fu_302_p2;
reg   [0:0] icmp_ln69_1_reg_406;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln71_fu_292_p1;
wire    ap_block_pp0_stage0;
reg   [30:0] c_fu_74;
wire    ap_loop_init;
reg   [30:0] r_fu_78;
wire   [30:0] select_ln68_1_fu_226_p3;
reg   [61:0] indvar_flatten_fu_82;
wire   [61:0] add_ln68_1_fu_186_p2;
wire   [31:0] tmp_fu_307_p11;
wire    ap_block_pp0_stage0_01001;
reg    M_e_0_ce0_local;
reg    M_e_1_ce0_local;
reg    M_e_2_ce0_local;
reg    M_e_3_ce0_local;
wire   [31:0] zext_ln69_fu_200_p1;
wire   [0:0] icmp_ln69_fu_204_p2;
wire   [30:0] add_ln68_fu_212_p2;
wire   [30:0] shl_ln71_fu_234_p2;
wire   [30:0] shl_ln71_1_fu_240_p2;
wire   [30:0] add_ln71_1_fu_246_p2;
wire   [30:0] select_ln68_fu_218_p3;
wire   [14:0] trunc_ln71_fu_252_p1;
wire   [14:0] lshr_ln_fu_260_p4;
wire   [31:0] zext_ln69_1_fu_299_p1;
wire   [31:0] tmp_fu_307_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_307_p1;
wire   [1:0] tmp_fu_307_p3;
wire  signed [1:0] tmp_fu_307_p5;
wire  signed [1:0] tmp_fu_307_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 c_fu_74 = 31'd0;
#0 r_fu_78 = 31'd0;
#0 indvar_flatten_fu_82 = 62'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) fmm_reduce_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U135(
    .din0(M_e_0_q0),
    .din1(M_e_1_q0),
    .din2(M_e_2_q0),
    .din3(M_e_3_q0),
    .def(tmp_fu_307_p9),
    .sel(trunc_ln69_reg_371_pp0_iter3_reg),
    .dout(tmp_fu_307_p11)
);

fmm_reduce_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            c_fu_74 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln68_reg_367 == 1'd0))) begin
            c_fu_74 <= add_ln69_fu_276_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 62'd0;
        end else if (((icmp_ln68_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln68_1_fu_186_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            r_fu_78 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln68_reg_367 == 1'd0))) begin
            r_fu_78 <= select_ln68_1_fu_226_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln69_reg_381 <= add_ln69_fu_276_p2;
        add_ln71_reg_376 <= add_ln71_fu_270_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln69_1_reg_406 <= icmp_ln69_1_fu_302_p2;
        trunc_ln69_reg_371 <= trunc_ln69_fu_256_p1;
        trunc_ln69_reg_371_pp0_iter3_reg <= trunc_ln69_reg_371;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        cmp4123_reg_363 <= cmp4123_fu_157_p2;
        icmp_ln68_reg_367 <= icmp_ln68_fu_181_p2;
    end
end

always @ (*) begin
    if (((cmp4123_reg_363 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln69_1_reg_406 == 1'd0))) begin
        A_dram_ap_vld = 1'b1;
    end else begin
        A_dram_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_0_ce0_local = 1'b1;
    end else begin
        M_e_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_1_ce0_local = 1'b1;
    end else begin
        M_e_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_2_ce0_local = 1'b1;
    end else begin
        M_e_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_3_ce0_local = 1'b1;
    end else begin
        M_e_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_fu_181_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln68_reg_367 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_dram = tmp_fu_307_p11;

assign M_e_0_address0 = zext_ln71_fu_292_p1;

assign M_e_0_ce0 = M_e_0_ce0_local;

assign M_e_1_address0 = zext_ln71_fu_292_p1;

assign M_e_1_ce0 = M_e_1_ce0_local;

assign M_e_2_address0 = zext_ln71_fu_292_p1;

assign M_e_2_ce0 = M_e_2_ce0_local;

assign M_e_3_address0 = zext_ln71_fu_292_p1;

assign M_e_3_ce0 = M_e_3_ce0_local;

assign add_ln68_1_fu_186_p2 = (indvar_flatten_fu_82 + 62'd1);

assign add_ln68_fu_212_p2 = (r_fu_78 + 31'd1);

assign add_ln69_fu_276_p2 = (select_ln68_fu_218_p3 + 31'd1);

assign add_ln71_1_fu_246_p2 = (shl_ln71_fu_234_p2 + shl_ln71_1_fu_240_p2);

assign add_ln71_fu_270_p2 = (trunc_ln71_fu_252_p1 + lshr_ln_fu_260_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign cmp4123_fu_157_p2 = (($signed(cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_181_p2 = ((indvar_flatten_fu_82 == bound) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_302_p2 = (($signed(zext_ln69_1_fu_299_p1) < $signed(cols)) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_204_p2 = (($signed(zext_ln69_fu_200_p1) < $signed(cols)) ? 1'b1 : 1'b0);

assign lshr_ln_fu_260_p4 = {{select_ln68_fu_218_p3[16:2]}};

assign select_ln68_1_fu_226_p3 = ((icmp_ln69_fu_204_p2[0:0] == 1'b1) ? r_fu_78 : add_ln68_fu_212_p2);

assign select_ln68_fu_218_p3 = ((icmp_ln69_fu_204_p2[0:0] == 1'b1) ? c_fu_74 : 31'd0);

assign shl_ln71_1_fu_240_p2 = select_ln68_1_fu_226_p3 << 31'd4;

assign shl_ln71_fu_234_p2 = select_ln68_1_fu_226_p3 << 31'd6;

assign tmp_fu_307_p9 = 'bx;

assign trunc_ln69_fu_256_p1 = select_ln68_fu_218_p3[1:0];

assign trunc_ln71_fu_252_p1 = add_ln71_1_fu_246_p2[14:0];

assign zext_ln69_1_fu_299_p1 = add_ln69_reg_381;

assign zext_ln69_fu_200_p1 = c_fu_74;

assign zext_ln71_fu_292_p1 = add_ln71_reg_376;

endmodule //fmm_reduce_kernel_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2
