// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_load_matrix_from_dram (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_dram_read,
        rows,
        cols,
        t_capacity,
        M_rows,
        M_rows_ap_vld,
        M_cols,
        M_cols_ap_vld,
        M_t,
        M_t_ap_vld,
        M_t_capacity,
        M_t_capacity_ap_vld,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_we0,
        M_e_0_d0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_we0,
        M_e_1_d0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_we0,
        M_e_2_d0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_we0,
        M_e_3_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] A_dram_read;
input  [31:0] rows;
input  [31:0] cols;
input  [31:0] t_capacity;
output  [31:0] M_rows;
output   M_rows_ap_vld;
output  [31:0] M_cols;
output   M_cols_ap_vld;
output  [31:0] M_t;
output   M_t_ap_vld;
output  [31:0] M_t_capacity;
output   M_t_capacity_ap_vld;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
output   M_e_0_we0;
output  [31:0] M_e_0_d0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
output   M_e_1_we0;
output  [31:0] M_e_1_d0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
output   M_e_2_we0;
output  [31:0] M_e_2_d0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
output   M_e_3_we0;
output  [31:0] M_e_3_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg M_rows_ap_vld;
reg M_cols_ap_vld;
reg M_t_ap_vld;
reg M_t_capacity_ap_vld;
reg[14:0] M_e_0_address0;
reg M_e_0_ce0;
reg M_e_0_we0;
reg[31:0] M_e_0_d0;
reg[14:0] M_e_1_address0;
reg M_e_1_ce0;
reg M_e_1_we0;
reg[31:0] M_e_1_d0;
reg[14:0] M_e_2_address0;
reg M_e_2_ce0;
reg M_e_2_we0;
reg[31:0] M_e_2_d0;
reg[14:0] M_e_3_address0;
reg M_e_3_ce0;
reg M_e_3_we0;
reg[31:0] M_e_3_d0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [30:0] smax_fu_147_p3;
reg   [30:0] smax_reg_188;
wire   [30:0] smax2_fu_161_p3;
reg   [30:0] smax2_reg_193;
wire    ap_CS_fsm_state3;
wire   [61:0] bound5_fu_96_p2;
reg   [61:0] bound5_reg_203;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_idle;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_ready;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_d0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_idle;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_ready;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_d0;
wire   [14:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_address0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_ce0;
wire    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_we0;
wire   [31:0] grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_d0;
reg    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg;
reg    grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [30:0] bound5_fu_96_p0;
wire   [30:0] bound5_fu_96_p1;
wire   [0:0] icmp_ln45_fu_101_p2;
wire   [0:0] empty_23_fu_141_p2;
wire   [30:0] empty_22_fu_125_p1;
wire   [0:0] empty_24_fu_155_p2;
wire   [30:0] empty_fu_121_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire   [61:0] bound5_fu_96_p00;
wire   [61:0] bound5_fu_96_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg = 1'b0;
#0 grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg = 1'b0;
end

fmm_reduce_kernel_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2 grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start),
    .ap_done(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done),
    .ap_idle(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_idle),
    .ap_ready(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_ready),
    .M_e_0_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_address0),
    .M_e_0_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_ce0),
    .M_e_0_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_we0),
    .M_e_0_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_d0),
    .M_e_1_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_address0),
    .M_e_1_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_ce0),
    .M_e_1_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_we0),
    .M_e_1_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_d0),
    .M_e_2_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_address0),
    .M_e_2_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_ce0),
    .M_e_2_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_we0),
    .M_e_2_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_d0),
    .M_e_3_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_address0),
    .M_e_3_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_ce0),
    .M_e_3_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_we0),
    .M_e_3_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_d0)
);

fmm_reduce_kernel_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4 grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start),
    .ap_done(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done),
    .ap_idle(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_idle),
    .ap_ready(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_ready),
    .cols(cols),
    .bound5(bound5_reg_203),
    .A_dram_read(A_dram_read),
    .M_e_0_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_address0),
    .M_e_0_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_ce0),
    .M_e_0_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_we0),
    .M_e_0_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_d0),
    .M_e_1_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_address0),
    .M_e_1_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_ce0),
    .M_e_1_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_we0),
    .M_e_1_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_d0),
    .M_e_2_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_address0),
    .M_e_2_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_ce0),
    .M_e_2_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_we0),
    .M_e_2_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_d0),
    .M_e_3_address0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_address0),
    .M_e_3_ce0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_ce0),
    .M_e_3_we0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_we0),
    .M_e_3_d0(grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_d0)
);

fmm_reduce_kernel_mul_31ns_31ns_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_1_1_U12(
    .din0(bound5_fu_96_p0),
    .din1(bound5_fu_96_p1),
    .dout(bound5_fu_96_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_ready == 1'b1)) begin
            grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_ready == 1'b1)) begin
            grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound5_reg_203 <= bound5_fu_96_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        smax2_reg_193 <= smax2_fu_161_p3;
        smax_reg_188 <= smax_fu_147_p3;
    end
end

always @ (*) begin
    if (((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        M_cols_ap_vld = 1'b1;
    end else begin
        M_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_0_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_0_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_address0;
    end else begin
        M_e_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_0_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_0_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_ce0;
    end else begin
        M_e_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_0_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_0_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_d0;
    end else begin
        M_e_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_0_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_0_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_0_we0;
    end else begin
        M_e_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_1_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_1_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_address0;
    end else begin
        M_e_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_1_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_1_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_ce0;
    end else begin
        M_e_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_1_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_1_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_d0;
    end else begin
        M_e_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_1_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_1_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_1_we0;
    end else begin
        M_e_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_2_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_2_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_address0;
    end else begin
        M_e_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_2_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_2_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_ce0;
    end else begin
        M_e_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_2_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_2_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_d0;
    end else begin
        M_e_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_2_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_2_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_2_we0;
    end else begin
        M_e_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_3_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_3_address0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_address0;
    end else begin
        M_e_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_3_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_3_ce0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_ce0;
    end else begin
        M_e_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_3_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_3_d0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_d0;
    end else begin
        M_e_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        M_e_3_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_M_e_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_e_3_we0 = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_M_e_3_we0;
    end else begin
        M_e_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        M_rows_ap_vld = 1'b1;
    end else begin
        M_rows_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done == 1'b1))) begin
        M_t_ap_vld = 1'b1;
    end else begin
        M_t_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        M_t_capacity_ap_vld = 1'b1;
    end else begin
        M_t_capacity_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_cols = cols;

assign M_rows = rows;

assign M_t = 32'd0;

assign M_t_capacity = ((icmp_ln45_fu_101_p2[0:0] == 1'b1) ? 32'd64 : t_capacity);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign bound5_fu_96_p0 = bound5_fu_96_p00;

assign bound5_fu_96_p00 = smax_reg_188;

assign bound5_fu_96_p1 = bound5_fu_96_p10;

assign bound5_fu_96_p10 = smax2_reg_193;

assign empty_22_fu_125_p1 = rows[30:0];

assign empty_23_fu_141_p2 = (($signed(rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_24_fu_155_p2 = (($signed(cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_121_p1 = cols[30:0];

assign grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68_ap_start_reg;

assign grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start = grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80_ap_start_reg;

assign icmp_ln45_fu_101_p2 = (($signed(t_capacity) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign smax2_fu_161_p3 = ((empty_24_fu_155_p2[0:0] == 1'b1) ? empty_fu_121_p1 : 31'd0);

assign smax_fu_147_p3 = ((empty_23_fu_141_p2[0:0] == 1'b1) ? empty_22_fu_125_p1 : 31'd0);

endmodule //fmm_reduce_kernel_load_matrix_from_dram
