// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_compute_pp_nn (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        r1,
        r2,
        M_cols,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_q0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_q0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_q0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_q0,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] r1;
input  [8:0] r2;
input  [31:0] M_cols;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
input  [31:0] M_e_0_q0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
input  [31:0] M_e_1_q0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
input  [31:0] M_e_2_q0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
input  [31:0] M_e_3_q0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [14:0] trunc_ln106_fu_104_p1;
reg   [14:0] trunc_ln106_reg_169;
wire   [14:0] add_ln104_fu_129_p2;
reg   [14:0] add_ln104_reg_174;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_done;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_idle;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_ready;
wire   [31:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_pp_write_assign_out;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_pp_write_assign_out_ap_vld;
wire   [31:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_nn_write_assign_out;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_nn_write_assign_out_ap_vld;
wire   [14:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_address0;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_ce0;
wire   [14:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_address0;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_ce0;
wire   [14:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_address0;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_ce0;
wire   [14:0] grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_address0;
wire    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_ce0;
reg    grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [30:0] shl_ln106_fu_86_p2;
wire   [30:0] shl_ln106_1_fu_92_p2;
wire   [30:0] add_ln106_fu_98_p2;
wire   [12:0] tmp_5_fu_117_p3;
wire   [14:0] tmp_fu_109_p3;
wire   [14:0] zext_ln104_fu_125_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg = 1'b0;
end

fmm_reduce_kernel_compute_pp_nn_Pipeline_VITIS_LOOP_104_1 grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start),
    .ap_done(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_done),
    .ap_idle(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_idle),
    .ap_ready(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_ready),
    .cols_non_t(M_cols),
    .mul_ln106(trunc_ln106_reg_169),
    .mul_ln108(add_ln104_reg_174),
    .pp_write_assign_out(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_pp_write_assign_out),
    .pp_write_assign_out_ap_vld(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_pp_write_assign_out_ap_vld),
    .nn_write_assign_out(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_nn_write_assign_out),
    .nn_write_assign_out_ap_vld(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_nn_write_assign_out_ap_vld),
    .M_e_0_address0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_address0),
    .M_e_0_ce0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_ce0),
    .M_e_0_q0(M_e_0_q0),
    .M_e_1_address0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_address0),
    .M_e_1_ce0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_ce0),
    .M_e_1_q0(M_e_1_q0),
    .M_e_2_address0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_address0),
    .M_e_2_ce0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_ce0),
    .M_e_2_q0(M_e_2_q0),
    .M_e_3_address0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_address0),
    .M_e_3_ce0(grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_ce0),
    .M_e_3_q0(M_e_3_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_ready == 1'b1)) begin
            grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln104_reg_174[14 : 4] <= add_ln104_fu_129_p2[14 : 4];
        trunc_ln106_reg_169 <= trunc_ln106_fu_104_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_e_0_address0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_address0;

assign M_e_0_ce0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_0_ce0;

assign M_e_1_address0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_address0;

assign M_e_1_ce0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_1_ce0;

assign M_e_2_address0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_address0;

assign M_e_2_ce0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_2_ce0;

assign M_e_3_address0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_address0;

assign M_e_3_ce0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_M_e_3_ce0;

assign add_ln104_fu_129_p2 = (tmp_fu_109_p3 + zext_ln104_fu_125_p1);

assign add_ln106_fu_98_p2 = (shl_ln106_fu_86_p2 + shl_ln106_1_fu_92_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return_0 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_pp_write_assign_out;

assign ap_return_1 = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_nn_write_assign_out;

assign grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start = grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64_ap_start_reg;

assign shl_ln106_1_fu_92_p2 = r1 << 31'd4;

assign shl_ln106_fu_86_p2 = r1 << 31'd6;

assign tmp_5_fu_117_p3 = {{r2}, {4'd0}};

assign tmp_fu_109_p3 = {{r2}, {6'd0}};

assign trunc_ln106_fu_104_p1 = add_ln106_fu_98_p2[14:0];

assign zext_ln104_fu_125_p1 = tmp_5_fu_117_p3;

always @ (posedge ap_clk) begin
    add_ln104_reg_174[3:0] <= 4'b0000;
end

endmodule //fmm_reduce_kernel_compute_pp_nn
