-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    new_col_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln132 : IN STD_LOGIC_VECTOR (16 downto 0);
    M_e_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    M_e_ce0 : OUT STD_LOGIC;
    M_e_we0 : OUT STD_LOGIC;
    M_e_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    M_e_ce1 : OUT STD_LOGIC;
    M_e_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln133 : IN STD_LOGIC_VECTOR (16 downto 0);
    mul_ln144 : IN STD_LOGIC_VECTOR (16 downto 0);
    icmp_ln133 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp34_i_i : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln135_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln135_fu_131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln137_fu_143_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln137_reg_246 : STD_LOGIC_VECTOR (16 downto 0);
    signal M_e_addr_5_reg_252 : STD_LOGIC_VECTOR (16 downto 0);
    signal M_e_addr_7_reg_258 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal M_e_addr_reg_264 : STD_LOGIC_VECTOR (16 downto 0);
    signal M_e_addr_reg_264_pp0_iter1_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal e1_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal e1_reg_269_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln140_reg_280 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal and_ln141_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln141_reg_284 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln141_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln141_reg_288 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_1_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_1_reg_292 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln137_fu_153_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln139_fu_167_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln144_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_2_fu_40 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln135_fu_137_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c : STD_LOGIC_VECTOR (30 downto 0);
    signal M_e_ce1_local : STD_LOGIC;
    signal M_e_address1_local : STD_LOGIC_VECTOR (16 downto 0);
    signal M_e_we0_local : STD_LOGIC;
    signal M_e_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal M_e_ce0_local : STD_LOGIC;
    signal M_e_address0_local : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_predicate_pred177_state5 : BOOLEAN;
    signal ap_predicate_pred177_state6 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal grp_fu_113_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln135_fu_127_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln137_fu_147_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln139_fu_163_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln144_fu_172_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln141_fu_181_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln141_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln141_fu_196_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln141_fu_196_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln141_1_fu_206_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln141_fu_200_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fmm_reduce_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    c_2_fu_40_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln135_fu_131_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_2_fu_40 <= add_ln135_fu_137_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_2_fu_40 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                M_e_addr_5_reg_252 <= zext_ln137_fu_153_p1(17 - 1 downto 0);
                    ap_predicate_pred177_state5 <= (((icmp_ln141_1_reg_292 = ap_const_lv1_1) and (or_ln141_reg_288 = ap_const_lv1_0) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)) or ((ap_const_lv1_1 = and_ln141_reg_284) and (or_ln141_reg_288 = ap_const_lv1_1) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)));
                icmp_ln135_reg_242 <= icmp_ln135_fu_131_p2;
                trunc_ln137_reg_246 <= trunc_ln137_fu_143_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                M_e_addr_7_reg_258 <= zext_ln139_fu_167_p1(17 - 1 downto 0);
                M_e_addr_reg_264 <= zext_ln144_fu_176_p1(17 - 1 downto 0);
                M_e_addr_reg_264_pp0_iter1_reg <= M_e_addr_reg_264;
                    ap_predicate_pred177_state6 <= (((icmp_ln141_1_reg_292 = ap_const_lv1_1) and (or_ln141_reg_288 = ap_const_lv1_0) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)) or ((ap_const_lv1_1 = and_ln141_reg_284) and (or_ln141_reg_288 = ap_const_lv1_1) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)));
                e1_reg_269_pp0_iter1_reg <= e1_reg_269;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                and_ln141_reg_284 <= and_ln141_fu_186_p2;
                icmp_ln141_1_reg_292 <= icmp_ln141_1_fu_209_p2;
                or_ln141_reg_288 <= or_ln141_fu_191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                e1_reg_269 <= M_e_q1;
                icmp_ln138_reg_276 <= grp_fu_113_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                icmp_ln140_reg_280 <= grp_fu_113_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    M_e_address0 <= M_e_address0_local;

    M_e_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, M_e_addr_5_reg_252, M_e_addr_7_reg_258, ap_CS_fsm_pp0_stage1, M_e_addr_reg_264_pp0_iter1_reg, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                M_e_address0_local <= M_e_addr_reg_264_pp0_iter1_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                M_e_address0_local <= M_e_addr_7_reg_258;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                M_e_address0_local <= M_e_addr_5_reg_252;
            else 
                M_e_address0_local <= "XXXXXXXXXXXXXXXXX";
            end if;
        else 
            M_e_address0_local <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_address1 <= M_e_address1_local;

    M_e_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, zext_ln137_fu_153_p1, ap_block_pp0_stage0, zext_ln139_fu_167_p1, ap_block_pp0_stage1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            M_e_address1_local <= zext_ln139_fu_167_p1(17 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            M_e_address1_local <= zext_ln137_fu_153_p1(17 - 1 downto 0);
        else 
            M_e_address1_local <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_ce0 <= M_e_ce0_local;

    M_e_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            M_e_ce0_local <= ap_const_logic_1;
        else 
            M_e_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_ce1 <= M_e_ce1_local;

    M_e_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            M_e_ce1_local <= ap_const_logic_1;
        else 
            M_e_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    M_e_d0 <= M_e_d0_local;

    M_e_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, e1_reg_269_pp0_iter1_reg, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            M_e_d0_local <= e1_reg_269_pp0_iter1_reg;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            M_e_d0_local <= ap_const_lv32_0;
        else 
            M_e_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    M_e_we0 <= M_e_we0_local;

    M_e_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln138_reg_276, icmp_ln140_reg_280, ap_block_pp0_stage2_11001, and_ln141_reg_284, or_ln141_reg_288, icmp_ln141_1_reg_292, ap_predicate_pred177_state5, ap_predicate_pred177_state6)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_pred177_state5 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln141_1_reg_292 = ap_const_lv1_1) and (or_ln141_reg_288 = ap_const_lv1_0) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)) or ((ap_const_lv1_1 = and_ln141_reg_284) and (or_ln141_reg_288 = ap_const_lv1_1) and (icmp_ln140_reg_280 = ap_const_lv1_0) and (icmp_ln138_reg_276 = ap_const_lv1_0)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_pred177_state6 = ap_const_boolean_1)))) then 
            M_e_we0_local <= ap_const_logic_1;
        else 
            M_e_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln135_fu_137_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c) + unsigned(ap_const_lv31_1));
    add_ln137_fu_147_p2 <= std_logic_vector(unsigned(mul_ln132) + unsigned(trunc_ln137_fu_143_p1));
    add_ln139_fu_163_p2 <= std_logic_vector(unsigned(mul_ln133) + unsigned(trunc_ln137_reg_246));
    add_ln144_fu_172_p2 <= std_logic_vector(unsigned(mul_ln144) + unsigned(trunc_ln137_reg_246));
    and_ln141_fu_186_p2 <= (icmp_ln141_fu_181_p2 and icmp_ln133);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln135_reg_242)
    begin
        if (((icmp_ln135_reg_242 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_2_fu_40, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_c <= c_2_fu_40;
        end if; 
    end process;

    grp_fu_113_p0 <= M_e_q1;
    grp_fu_113_p2 <= "1" when (grp_fu_113_p0 = ap_const_lv32_0) else "0";
    icmp_ln135_fu_131_p2 <= "1" when (signed(zext_ln135_fu_127_p1) < signed(new_col_3)) else "0";
    icmp_ln141_1_fu_209_p2 <= "1" when (sext_ln141_1_fu_206_p1 = sub_ln141_fu_200_p2) else "0";
    icmp_ln141_fu_181_p1 <= M_e_q1;
    icmp_ln141_fu_181_p2 <= "1" when (e1_reg_269 = icmp_ln141_fu_181_p1) else "0";
    or_ln141_fu_191_p2 <= (cmp34_i_i or and_ln141_fu_186_p2);
        sext_ln141_1_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(e1_reg_269),33));

    sext_ln141_fu_196_p0 <= M_e_q1;
        sext_ln141_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln141_fu_196_p0),33));

    sub_ln141_fu_200_p2 <= std_logic_vector(unsigned(ap_const_lv33_0) - unsigned(sext_ln141_fu_196_p1));
    trunc_ln137_fu_143_p1 <= ap_sig_allocacmp_c(17 - 1 downto 0);
    zext_ln135_fu_127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_c),32));
    zext_ln137_fu_153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln137_fu_147_p2),64));
    zext_ln139_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln139_fu_163_p2),64));
    zext_ln144_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln144_fu_172_p2),64));
end behav;
