set SynModuleInfo {
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME fmm_reduce_kernel_entry_proc}
  {SRCNAME Block_entry_proc.1 MODELNAME Block_entry_proc_1 RTLNAME fmm_reduce_kernel_Block_entry_proc_1
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_mul_32s_32s_64_1_1 RTLNAME fmm_reduce_kernel_mul_32s_32s_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_50_1_VITIS_LOOP_52_2 MODELNAME load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_50_1_VITIS_LOOP_52_2 RTLNAME fmm_reduce_kernel_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_50_1_VITIS_LOOP_52_2
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_flow_control_loop_pipe_sequential_init RTLNAME fmm_reduce_kernel_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME fmm_reduce_kernel_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_59_3_VITIS_LOOP_60_4 MODELNAME load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_59_3_VITIS_LOOP_60_4 RTLNAME fmm_reduce_kernel_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_59_3_VITIS_LOOP_60_4
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_mul_32s_31ns_62_1_1 RTLNAME fmm_reduce_kernel_mul_32s_31ns_62_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME load_matrix_from_dram_safe MODELNAME load_matrix_from_dram_safe RTLNAME fmm_reduce_kernel_load_matrix_from_dram_safe
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_mul_31ns_31ns_62_1_1 RTLNAME fmm_reduce_kernel_mul_31ns_31ns_62_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_1 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_1 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_1}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_1 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_1 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_1}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_13 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_13 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_13}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_1 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_1 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_1}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_1 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_1 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_1}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_1 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_1 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_1}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_2 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_2 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_2}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_3 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_3 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_3}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_14 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_14 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_14}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_15 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_15 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_15}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_16 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_16 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_193_2_VITIS_LOOP_116_16}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_17 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_17 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_158_17}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_28 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_28 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_164_28}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_39 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_39 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_175_39}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_110 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_110 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_136_110}
  {SRCNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_111 MODELNAME greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_111 RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_93_111}
  {SRCNAME greedy_potential_reduce_with_debug MODELNAME greedy_potential_reduce_with_debug RTLNAME fmm_reduce_kernel_greedy_potential_reduce_with_debug
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_mul_32ns_34ns_64_1_1 RTLNAME fmm_reduce_kernel_mul_32ns_34ns_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME fmm_reduce_kernel_mul_32s_32s_32_1_1 RTLNAME fmm_reduce_kernel_mul_32s_32s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME fmm_reduce_kernel_mul_64ns_31ns_95_3_1 RTLNAME fmm_reduce_kernel_mul_64ns_31ns_95_3_1 BINDTYPE op TYPE mul IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2 MODELNAME store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2 RTLNAME fmm_reduce_kernel_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2}
  {SRCNAME store_matrix_to_dram_safe MODELNAME store_matrix_to_dram_safe RTLNAME fmm_reduce_kernel_store_matrix_to_dram_safe}
  {SRCNAME Block_entry_proc MODELNAME Block_entry_proc RTLNAME fmm_reduce_kernel_Block_entry_proc
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_Block_entry_proc_M_e_RAM_AUTO_1R1W RTLNAME fmm_reduce_kernel_Block_entry_proc_M_e_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME fmm_reduce_kernel MODELNAME fmm_reduce_kernel RTLNAME fmm_reduce_kernel IS_TOP 1
    SUBMODULES {
      {MODELNAME fmm_reduce_kernel_fifo_w64_d3_S RTLNAME fmm_reduce_kernel_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME A_dram_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d3_S RTLNAME fmm_reduce_kernel_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME t_capacity_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d3_S RTLNAME fmm_reduce_kernel_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME k1_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d3_S RTLNAME fmm_reduce_kernel_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME k2_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w64_d3_S RTLNAME fmm_reduce_kernel_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME debug_dram_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d2_S RTLNAME fmm_reduce_kernel_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME rows_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d2_S RTLNAME fmm_reduce_kernel_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME cols_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w32_d2_S RTLNAME fmm_reduce_kernel_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME debug_capacity_c_U}
      {MODELNAME fmm_reduce_kernel_fifo_w1_d2_S RTLNAME fmm_reduce_kernel_fifo_w1_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME spec_select_loc_channel_U}
      {MODELNAME fmm_reduce_kernel_fifo_w1_d2_S RTLNAME fmm_reduce_kernel_fifo_w1_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc_channel_U}
      {MODELNAME fmm_reduce_kernel_gmem_m_axi RTLNAME fmm_reduce_kernel_gmem_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME fmm_reduce_kernel_gmem2_m_axi RTLNAME fmm_reduce_kernel_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME fmm_reduce_kernel_control_s_axi RTLNAME fmm_reduce_kernel_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME fmm_reduce_kernel_control_r_s_axi RTLNAME fmm_reduce_kernel_control_r_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
