

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "8", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68"],
		"CDFG" : "fmm_reduce_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "5", "Name" : "entry_proc_U0"},
			{"ID" : "6", "Name" : "Block_entry_proc_1_U0"},
			{"ID" : "8", "Name" : "Block_entry_proc_U0"}],
		"OutputProcess" : [
			{"ID" : "8", "Name" : "Block_entry_proc_U0"}],
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "gmem"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "gmem2"}]},
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "verbose", "Type" : "None", "Direction" : "I"},
			{"Name" : "debug_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "debug_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "M_rows"}]},
			{"Name" : "M_cols", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "M_cols"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "M_t"}]},
			{"Name" : "M_t_capacity", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "M_t_capacity"}]},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "Block_entry_proc_U0", "Port" : "M_e"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_dram_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "59", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "A_dram_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "t_capacity_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "60", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "t_capacity_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k1_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "61", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "k1_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "62", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "k2_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "debug_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "debug_dram_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "63", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "debug_dram_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_1_U0", "Parent" : "0", "Child" : ["7"],
		"CDFG" : "Block_entry_proc_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "debug_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "rows_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "64", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "rows_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "cols_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "65", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "cols_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "debug_capacity_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "66", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "debug_capacity_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_1_U0.mul_32s_32s_64_1_1_U11", "Parent" : "6"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0", "Parent" : "0", "Child" : ["9", "10", "17", "54"],
		"CDFG" : "Block_entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "67", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "68", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "gmem", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "54", "SubInstance" : "grp_store_matrix_to_dram_safe_fu_218", "Port" : "gmem", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "A_dram", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "59", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "A_dram_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "rows", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "64", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "rows_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "cols", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "65", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "cols_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "t_capacity", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "60", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "t_capacity_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "k1", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "61", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "k1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "k2", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "62", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "k2_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "gmem2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "debug_dram", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "63", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "debug_dram_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "debug_capacity", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "66", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "debug_capacity_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "M_rows", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "M_rows", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "M_rows", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "54", "SubInstance" : "grp_store_matrix_to_dram_safe_fu_218", "Port" : "M_rows", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "M_cols", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "M_cols", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "M_cols", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "54", "SubInstance" : "grp_store_matrix_to_dram_safe_fu_218", "Port" : "M_cols", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "M_t", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "M_t", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "M_t_capacity", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "M_t_capacity", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "M_t_capacity", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_load_matrix_from_dram_safe_fu_174", "Port" : "M_e", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "17", "SubInstance" : "grp_greedy_potential_reduce_with_debug_fu_198", "Port" : "M_e", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "54", "SubInstance" : "grp_store_matrix_to_dram_safe_fu_218", "Port" : "M_e", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.M_e_U", "Parent" : "8"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174", "Parent" : "8", "Child" : ["11", "13", "16"],
		"CDFG" : "load_matrix_from_dram_safe",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4_fu_78", "Port" : "gmem", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_72", "Port" : "M_e", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "13", "SubInstance" : "grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4_fu_78", "Port" : "M_e", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_rows", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_cols", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_t", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_t_capacity", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_72", "Parent" : "10", "Child" : ["12"],
		"CDFG" : "load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "102402", "EstimateLatencyMax" : "102402",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_1_VITIS_LOOP_51_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_72.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4_fu_78", "Parent" : "10", "Child" : ["14", "15"],
		"CDFG" : "load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln58", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln58", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_58_3_VITIS_LOOP_59_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "14", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4_fu_78.mul_32s_31ns_62_1_1_U20", "Parent" : "13"},
	{"ID" : "15", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.grp_load_matrix_from_dram_safe_Pipeline_VITIS_LOOP_58_3_VITIS_LOOP_59_4_fu_78.flow_control_loop_pipe_sequential_init_U", "Parent" : "13"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_load_matrix_from_dram_safe_fu_174.mul_31ns_31ns_62_1_1_U28", "Parent" : "10"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198", "Parent" : "8", "Child" : ["18", "20", "22", "24", "26", "28", "30", "32", "34", "36", "38", "40", "42", "44", "46", "48", "50", "51", "52", "53"],
		"CDFG" : "greedy_potential_reduce_with_debug",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "debug_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "debug_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_1_fu_895", "Port" : "M_e", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "20", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_1_fu_904", "Port" : "M_e", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "22", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_13_fu_915", "Port" : "M_e", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "24", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_1_fu_925", "Port" : "M_e", "Inst_start_state" : "24", "Inst_end_state" : "25"},
					{"ID" : "26", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_1_fu_935", "Port" : "M_e", "Inst_start_state" : "30", "Inst_end_state" : "31"},
					{"ID" : "28", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_1_fu_948", "Port" : "M_e", "Inst_start_state" : "33", "Inst_end_state" : "34"},
					{"ID" : "30", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_2_fu_957", "Port" : "M_e", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "32", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_3_fu_968", "Port" : "M_e", "Inst_start_state" : "40", "Inst_end_state" : "41"},
					{"ID" : "34", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_14_fu_979", "Port" : "M_e", "Inst_start_state" : "44", "Inst_end_state" : "45"},
					{"ID" : "36", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_15_fu_989", "Port" : "M_e", "Inst_start_state" : "48", "Inst_end_state" : "49"},
					{"ID" : "38", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_16_fu_999", "Port" : "M_e", "Inst_start_state" : "54", "Inst_end_state" : "55"},
					{"ID" : "40", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_17_fu_1012", "Port" : "M_e", "Inst_start_state" : "57", "Inst_end_state" : "58"},
					{"ID" : "42", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_28_fu_1021", "Port" : "M_e", "Inst_start_state" : "60", "Inst_end_state" : "61"},
					{"ID" : "44", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_39_fu_1032", "Port" : "M_e", "Inst_start_state" : "64", "Inst_end_state" : "65"},
					{"ID" : "46", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110_fu_1043", "Port" : "M_e", "Inst_start_state" : "68", "Inst_end_state" : "69"},
					{"ID" : "48", "SubInstance" : "grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_111_fu_1055", "Port" : "M_e", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "M_t_capacity", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_191_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "82", "FirstState" : "ap_ST_fsm_state26", "LastState" : ["ap_ST_fsm_state32"], "QuitState" : ["ap_ST_fsm_state26"], "PreState" : ["ap_ST_fsm_state25"], "PostState" : ["ap_ST_fsm_state33", "ap_ST_fsm_state41"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_191_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "82", "FirstState" : "ap_ST_fsm_state50", "LastState" : ["ap_ST_fsm_state56"], "QuitState" : ["ap_ST_fsm_state50"], "PreState" : ["ap_ST_fsm_state49"], "PostState" : ["ap_ST_fsm_state57", "ap_ST_fsm_state65"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_224_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "82", "FirstState" : "ap_ST_fsm_state17", "LastState" : ["ap_ST_fsm_state66"], "QuitState" : ["ap_ST_fsm_state18"], "PreState" : ["ap_ST_fsm_state16"], "PostState" : ["ap_ST_fsm_state16"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_223_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "82", "FirstState" : "ap_ST_fsm_state16", "LastState" : ["ap_ST_fsm_state18"], "QuitState" : ["ap_ST_fsm_state16"], "PreState" : ["ap_ST_fsm_state15"], "PostState" : ["ap_ST_fsm_state81", "ap_ST_fsm_state67", "ap_ST_fsm_state70"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_259_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "82", "FirstState" : "ap_ST_fsm_state15", "LastState" : ["ap_ST_fsm_state82"], "QuitState" : ["ap_ST_fsm_state15"], "PreState" : ["ap_ST_fsm_state14"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_1_fu_895", "Parent" : "17", "Child" : ["19"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "total_rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln250", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_103_1_VITIS_LOOP_92_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "19", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_1_fu_895.flow_control_loop_pipe_sequential_init_U", "Parent" : "18"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_1_fu_904", "Parent" : "17", "Child" : ["21"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "j_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "n_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "21", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_1_fu_904.flow_control_loop_pipe_sequential_init_U", "Parent" : "20"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_13_fu_915", "Parent" : "17", "Child" : ["23"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_13",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "j_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "23", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_13_fu_915.flow_control_loop_pipe_sequential_init_U", "Parent" : "22"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_1_fu_925", "Parent" : "17", "Child" : ["25"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "new_col", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "mul_ln119277", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln144_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_135_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "25", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_1_fu_925.flow_control_loop_pipe_sequential_init_U", "Parent" : "24"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_1_fu_935", "Parent" : "17", "Child" : ["27"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln192", "Type" : "None", "Direction" : "I"},
			{"Name" : "s_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln191", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s_9_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_192_2_VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "27", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_1_fu_935.flow_control_loop_pipe_sequential_init_U", "Parent" : "26"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_1_fu_948", "Parent" : "17", "Child" : ["29"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "rowt", "Type" : "None", "Direction" : "I"},
			{"Name" : "idxprom4_i12_i332_i_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row1_ce_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_157_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "29", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_1_fu_948.flow_control_loop_pipe_sequential_init_U", "Parent" : "28"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_2_fu_957", "Parent" : "17", "Child" : ["31"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln163", "Type" : "None", "Direction" : "I"},
			{"Name" : "idxprom4_i12_i332_i_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln163", "Type" : "None", "Direction" : "I"},
			{"Name" : "move_type_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row2_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_163_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_2_fu_957.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_3_fu_968", "Parent" : "17", "Child" : ["33"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "move_type_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "colt", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln176", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "mul_ln172", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln173", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_174_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "33", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_3_fu_968.flow_control_loop_pipe_sequential_init_U", "Parent" : "32"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_14_fu_979", "Parent" : "17", "Child" : ["35"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_14",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "j_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "n_6_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_115_14_fu_979.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_15_fu_989", "Parent" : "17", "Child" : ["37"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_15",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "new_col_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "mul_ln119274", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln144_2", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_135_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "37", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_15_fu_989.flow_control_loop_pipe_sequential_init_U", "Parent" : "36"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_16_fu_999", "Parent" : "17", "Child" : ["39"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_16",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln192_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "s_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln191_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln117_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s_16_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_192_2_VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_192_2_VITIS_LOOP_115_16_fu_999.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_17_fu_1012", "Parent" : "17", "Child" : ["41"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_17",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "rowt_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "idxprom4_i12_i_i_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row1_3_ce_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_157_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "41", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_157_17_fu_1012.flow_control_loop_pipe_sequential_init_U", "Parent" : "40"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_28_fu_1021", "Parent" : "17", "Child" : ["43"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_28",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln163_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "idxprom4_i12_i_i_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln163_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "move_type_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row2_4_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_163_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_163_28_fu_1021.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_39_fu_1032", "Parent" : "17", "Child" : ["45"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_39",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "move_type_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "colt_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln176_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "mul_ln172_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln173_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_174_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "45", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_174_39_fu_1032.flow_control_loop_pipe_sequential_init_U", "Parent" : "44"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110_fu_1043", "Parent" : "17", "Child" : ["47"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "new_col_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln132", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "mul_ln133", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln144", "Type" : "None", "Direction" : "I"},
			{"Name" : "icmp_ln133", "Type" : "None", "Direction" : "I"},
			{"Name" : "cmp34_i_i", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_135_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "47", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_135_110_fu_1043.flow_control_loop_pipe_sequential_init_U", "Parent" : "46"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_111_fu_1055", "Parent" : "17", "Child" : ["49"],
		"CDFG" : "greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_111",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "total_rows_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln266", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s_3_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_103_1_VITIS_LOOP_92_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.grp_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_103_1_VITIS_LOOP_92_111_fu_1055.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.mul_31ns_31ns_62_1_1_U127", "Parent" : "17"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.mul_32ns_34ns_64_1_1_U128", "Parent" : "17"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.mul_32s_32s_32_1_1_U129", "Parent" : "17"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_greedy_potential_reduce_with_debug_fu_198.mul_64ns_31ns_95_3_1_U130", "Parent" : "17"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_store_matrix_to_dram_safe_fu_218", "Parent" : "8", "Child" : ["55", "58"],
		"CDFG" : "store_matrix_to_dram_safe",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2_fu_40", "Port" : "gmem", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2_fu_40", "Port" : "M_e", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_store_matrix_to_dram_safe_fu_218.grp_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2_fu_40", "Parent" : "54", "Child" : ["56", "57"],
		"CDFG" : "store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_dram", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln76", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_76_1_VITIS_LOOP_77_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter10", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter10", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "56", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_store_matrix_to_dram_safe_fu_218.grp_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2_fu_40.mul_32s_31ns_62_1_1_U144", "Parent" : "55"},
	{"ID" : "57", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_store_matrix_to_dram_safe_fu_218.grp_store_matrix_to_dram_safe_Pipeline_VITIS_LOOP_76_1_VITIS_LOOP_77_2_fu_40.flow_control_loop_pipe_sequential_init_U", "Parent" : "55"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_store_matrix_to_dram_safe_fu_218.mul_31ns_31ns_62_1_1_U151", "Parent" : "54"},
	{"ID" : "59", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_dram_c_U", "Parent" : "0"},
	{"ID" : "60", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.t_capacity_c_U", "Parent" : "0"},
	{"ID" : "61", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k1_c_U", "Parent" : "0"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k2_c_U", "Parent" : "0"},
	{"ID" : "63", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.debug_dram_c_U", "Parent" : "0"},
	{"ID" : "64", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.rows_c_U", "Parent" : "0"},
	{"ID" : "65", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cols_c_U", "Parent" : "0"},
	{"ID" : "66", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.debug_capacity_c_U", "Parent" : "0"},
	{"ID" : "67", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spec_select_loc_channel_U", "Parent" : "0"},
	{"ID" : "68", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_loc_channel_U", "Parent" : "0"}]}
