

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "11", "42"],
		"CDFG" : "fmm_reduce_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_dram", "Type" : "None", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "A_dram", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_rows", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_rows", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_rows", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "M_cols", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_cols", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_cols", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_cols", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_t", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_t", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_t_capacity", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_t_capacity", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_t_capacity", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_e_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_e_0", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_e_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_e_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_e_1", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_e_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_e_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_e_2", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_e_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_load_matrix_from_dram_fu_104", "Port" : "M_e_3", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "11", "SubInstance" : "grp_greedy_potential_reduce_fu_132", "Port" : "M_e_3", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "42", "SubInstance" : "grp_store_matrix_to_dram_fu_156", "Port" : "M_e_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.M_e_0_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.M_e_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.M_e_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.M_e_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104", "Parent" : "0", "Child" : ["6", "8", "10"],
		"CDFG" : "load_matrix_from_dram",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_dram_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_cols", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_t", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_t_capacity", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68", "Port" : "M_e_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "8", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80", "Port" : "M_e_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68", "Port" : "M_e_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "8", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80", "Port" : "M_e_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68", "Port" : "M_e_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "8", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80", "Port" : "M_e_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68", "Port" : "M_e_3", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "8", "SubInstance" : "grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80", "Port" : "M_e_3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104.grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68", "Parent" : "5", "Child" : ["7"],
		"CDFG" : "load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "102402", "EstimateLatencyMax" : "102402",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_1_VITIS_LOOP_51_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104.grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_fu_68.flow_control_loop_pipe_sequential_init_U", "Parent" : "6"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104.grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80", "Parent" : "5", "Child" : ["9"],
		"CDFG" : "load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound5", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_dram_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_56_3_VITIS_LOOP_57_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104.grp_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4_fu_80.flow_control_loop_pipe_sequential_init_U", "Parent" : "8"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_load_matrix_from_dram_fu_104.mul_31ns_31ns_62_1_1_U12", "Parent" : "5"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132", "Parent" : "0", "Child" : ["12", "38"],
		"CDFG" : "greedy_potential_reduce",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_rows", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_t", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_cols", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_e_0", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "38", "SubInstance" : "grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224", "Port" : "M_e_0", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_e_1", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "38", "SubInstance" : "grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224", "Port" : "M_e_1", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_e_2", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "38", "SubInstance" : "grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224", "Port" : "M_e_2", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_e_3", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "38", "SubInstance" : "grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224", "Port" : "M_e_3", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "M_t_capacity", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_find_best_move_fu_202", "Port" : "M_t_capacity", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_232_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "7", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state7"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202", "Parent" : "11", "Child" : ["13", "18"],
		"CDFG" : "find_best_move",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_rows", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_t", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_pp_nn_fu_272", "Port" : "M_cols", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_cols", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_pp_nn_fu_272", "Port" : "M_e_0", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_e_0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_pp_nn_fu_272", "Port" : "M_e_1", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_e_1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_pp_nn_fu_272", "Port" : "M_e_2", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_e_2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_pp_nn_fu_272", "Port" : "M_e_3", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_e_3", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "M_t_capacity", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_compute_greedy_potential_score_fu_288", "Port" : "M_t_capacity", "Inst_start_state" : "9", "Inst_end_state" : "10"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_213_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "11", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state11"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_212_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "11", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_pp_nn_fu_272", "Parent" : "12", "Child" : ["14"],
		"CDFG" : "compute_pp_nn",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "r1", "Type" : "None", "Direction" : "I"},
			{"Name" : "r2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "14", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_pp_nn_fu_272.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Parent" : "13", "Child" : ["15", "16", "17"],
		"CDFG" : "compute_pp_nn_Pipeline_VITIS_LOOP_104_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln106", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln108", "Type" : "None", "Direction" : "I"},
			{"Name" : "pp_write_assign_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "nn_write_assign_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_104_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "15", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_pp_nn_fu_272.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.sparsemux_9_2_32_1_1_U26", "Parent" : "14"},
	{"ID" : "16", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_pp_nn_fu_272.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.sparsemux_9_2_32_1_1_U27", "Parent" : "14"},
	{"ID" : "17", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_pp_nn_fu_272.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.flow_control_loop_pipe_sequential_init_U", "Parent" : "14"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288", "Parent" : "12", "Child" : ["19", "24", "28", "31", "34", "37"],
		"CDFG" : "compute_greedy_potential_score",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "r1", "Type" : "None", "Direction" : "I"},
			{"Name" : "r2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sign", "Type" : "None", "Direction" : "I"},
			{"Name" : "k1", "Type" : "None", "Direction" : "I"},
			{"Name" : "k2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_pp_nn_fu_399", "Port" : "M_cols", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_pp_nn_fu_399", "Port" : "M_e_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "24", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417", "Port" : "M_e_0", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "28", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435", "Port" : "M_e_0", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "31", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451", "Port" : "M_e_0", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "34", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469", "Port" : "M_e_0", "Inst_start_state" : "21", "Inst_end_state" : "22"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_pp_nn_fu_399", "Port" : "M_e_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "24", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417", "Port" : "M_e_1", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "28", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435", "Port" : "M_e_1", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "31", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451", "Port" : "M_e_1", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "34", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469", "Port" : "M_e_1", "Inst_start_state" : "21", "Inst_end_state" : "22"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_pp_nn_fu_399", "Port" : "M_e_2", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "24", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417", "Port" : "M_e_2", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "28", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435", "Port" : "M_e_2", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "31", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451", "Port" : "M_e_2", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "34", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469", "Port" : "M_e_2", "Inst_start_state" : "21", "Inst_end_state" : "22"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_pp_nn_fu_399", "Port" : "M_e_3", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "24", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417", "Port" : "M_e_3", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "28", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435", "Port" : "M_e_3", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "31", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451", "Port" : "M_e_3", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "34", "SubInstance" : "grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469", "Port" : "M_e_3", "Inst_start_state" : "21", "Inst_end_state" : "22"}]},
			{"Name" : "M_t", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "M_t_capacity", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_181_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "23", "FirstState" : "ap_ST_fsm_state10", "LastState" : ["ap_ST_fsm_state13"], "QuitState" : ["ap_ST_fsm_state10"], "PreState" : ["ap_ST_fsm_state9"], "PostState" : ["ap_ST_fsm_state9"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_180_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "23", "FirstState" : "ap_ST_fsm_state9", "LastState" : ["ap_ST_fsm_state10"], "QuitState" : ["ap_ST_fsm_state9"], "PreState" : ["ap_ST_fsm_state8"], "PostState" : ["ap_ST_fsm_state14", "ap_ST_fsm_state22"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "19", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_pp_nn_fu_399", "Parent" : "18", "Child" : ["20"],
		"CDFG" : "compute_pp_nn",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "r1", "Type" : "None", "Direction" : "I"},
			{"Name" : "r2", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Port" : "M_e_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "20", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_pp_nn_fu_399.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64", "Parent" : "19", "Child" : ["21", "22", "23"],
		"CDFG" : "compute_pp_nn_Pipeline_VITIS_LOOP_104_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols_non_t", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln106", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln108", "Type" : "None", "Direction" : "I"},
			{"Name" : "pp_write_assign_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "nn_write_assign_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_104_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "21", "Level" : "6", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_pp_nn_fu_399.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.sparsemux_9_2_32_1_1_U26", "Parent" : "20"},
	{"ID" : "22", "Level" : "6", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_pp_nn_fu_399.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.sparsemux_9_2_32_1_1_U27", "Parent" : "20"},
	{"ID" : "23", "Level" : "6", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_pp_nn_fu_399.grp_compute_pp_nn_Pipeline_VITIS_LOOP_104_1_fu_64.flow_control_loop_pipe_sequential_init_U", "Parent" : "20"},
	{"ID" : "24", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417", "Parent" : "18", "Child" : ["25", "26", "27"],
		"CDFG" : "compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "new_col", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln121", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln122", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln133", "Type" : "None", "Direction" : "I"},
			{"Name" : "icmp_ln196", "Type" : "None", "Direction" : "I"},
			{"Name" : "cmp34_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_124_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "25", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417.sparsemux_9_2_32_1_1_U45", "Parent" : "24"},
	{"ID" : "26", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417.sparsemux_9_2_32_1_1_U46", "Parent" : "24"},
	{"ID" : "27", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_124_1_fu_417.flow_control_loop_pipe_sequential_init_U", "Parent" : "24"},
	{"ID" : "28", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435", "Parent" : "18", "Child" : ["29", "30"],
		"CDFG" : "compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "rowt", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln144", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln144", "Type" : "None", "Direction" : "I"},
			{"Name" : "row1_ce_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_146_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "29", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435.sparsemux_9_2_32_1_1_x_U57", "Parent" : "28"},
	{"ID" : "30", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_146_1_fu_435.flow_control_loop_pipe_sequential_init_U", "Parent" : "28"},
	{"ID" : "31", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451", "Parent" : "18", "Child" : ["32", "33"],
		"CDFG" : "compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln152", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln144", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln144", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln152", "Type" : "None", "Direction" : "I"},
			{"Name" : "move_type_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row2_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_152_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "32", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451.sparsemux_9_2_32_1_1_x_U67", "Parent" : "31"},
	{"ID" : "33", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2_fu_451.flow_control_loop_pipe_sequential_init_U", "Parent" : "31"},
	{"ID" : "34", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469", "Parent" : "18", "Child" : ["35", "36"],
		"CDFG" : "compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "move_type_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "colt", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln165", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln161", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln162", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_163_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state4", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state4_blk", "QuitState" : "ap_ST_fsm_state4", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state4_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469.sparsemux_9_2_32_1_1_U78", "Parent" : "34"},
	{"ID" : "36", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.grp_compute_greedy_potential_score_Pipeline_VITIS_LOOP_163_3_fu_469.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "37", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_find_best_move_fu_202.grp_compute_greedy_potential_score_fu_288.mul_32s_32s_32_1_1_U88", "Parent" : "18"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224", "Parent" : "11", "Child" : ["39", "40", "41"],
		"CDFG" : "greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "new_col", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln121", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln122", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln133", "Type" : "None", "Direction" : "I"},
			{"Name" : "icmp_ln122", "Type" : "None", "Direction" : "I"},
			{"Name" : "cmp34_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_124_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224.sparsemux_9_2_32_1_1_U113", "Parent" : "38"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224.sparsemux_9_2_32_1_1_U114", "Parent" : "38"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_greedy_potential_reduce_fu_132.grp_greedy_potential_reduce_Pipeline_VITIS_LOOP_124_1_fu_224.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_store_matrix_to_dram_fu_156", "Parent" : "0", "Child" : ["43", "46"],
		"CDFG" : "store_matrix_to_dram",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_dram", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Port" : "A_dram", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_rows", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Port" : "M_e_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Port" : "M_e_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Port" : "M_e_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Port" : "M_e_3", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_store_matrix_to_dram_fu_156.grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28", "Parent" : "42", "Child" : ["44", "45"],
		"CDFG" : "store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cols", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_dram", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "M_e_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M_e_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_68_1_VITIS_LOOP_69_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_store_matrix_to_dram_fu_156.grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28.sparsemux_9_2_32_1_1_U135", "Parent" : "43"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_store_matrix_to_dram_fu_156.grp_store_matrix_to_dram_Pipeline_VITIS_LOOP_68_1_VITIS_LOOP_69_2_fu_28.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_store_matrix_to_dram_fu_156.mul_31ns_31ns_62_1_1_U143", "Parent" : "42"}]}
