// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cols,
        bound5,
        A_dram_read,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_we0,
        M_e_0_d0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_we0,
        M_e_1_d0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_we0,
        M_e_2_d0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_we0,
        M_e_3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] cols;
input  [61:0] bound5;
input  [31:0] A_dram_read;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
output   M_e_0_we0;
output  [31:0] M_e_0_d0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
output   M_e_1_we0;
output  [31:0] M_e_1_d0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
output   M_e_2_we0;
output  [31:0] M_e_2_d0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
output   M_e_3_we0;
output  [31:0] M_e_3_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln56_fu_166_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln56_reg_333;
wire   [1:0] trunc_ln57_fu_241_p1;
reg   [1:0] trunc_ln57_reg_337;
wire   [14:0] add_ln59_fu_255_p2;
reg   [14:0] add_ln59_reg_341;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln59_fu_287_p1;
wire    ap_block_pp0_stage0;
reg   [30:0] c_1_fu_66;
wire   [30:0] add_ln57_fu_271_p2;
wire    ap_loop_init;
reg   [30:0] r_fu_70;
wire   [30:0] select_ln56_1_fu_211_p3;
reg   [61:0] indvar_flatten7_fu_74;
wire   [61:0] add_ln56_1_fu_171_p2;
reg    M_e_2_we0_local;
reg    M_e_2_ce0_local;
reg    M_e_1_we0_local;
reg    M_e_1_ce0_local;
reg    M_e_0_we0_local;
reg    M_e_0_ce0_local;
reg    M_e_3_we0_local;
reg    M_e_3_ce0_local;
wire   [31:0] zext_ln57_fu_185_p1;
wire   [0:0] icmp_ln57_fu_189_p2;
wire   [30:0] add_ln56_fu_197_p2;
wire   [30:0] shl_ln59_fu_219_p2;
wire   [30:0] shl_ln59_1_fu_225_p2;
wire   [30:0] add_ln59_1_fu_231_p2;
wire   [30:0] select_ln56_fu_203_p3;
wire   [14:0] trunc_ln59_fu_237_p1;
wire   [14:0] lshr_ln1_fu_245_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 c_1_fu_66 = 31'd0;
#0 r_fu_70 = 31'd0;
#0 indvar_flatten7_fu_74 = 62'd0;
#0 ap_done_reg = 1'b0;
end

fmm_reduce_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            c_1_fu_66 <= 31'd0;
        end else if (((icmp_ln56_reg_333 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            c_1_fu_66 <= add_ln57_fu_271_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_74 <= 62'd0;
        end else if (((icmp_ln56_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten7_fu_74 <= add_ln56_1_fu_171_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            r_fu_70 <= 31'd0;
        end else if (((icmp_ln56_reg_333 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            r_fu_70 <= select_ln56_1_fu_211_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln59_reg_341 <= add_ln59_fu_255_p2;
        trunc_ln57_reg_337 <= trunc_ln57_fu_241_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln56_reg_333 <= icmp_ln56_fu_166_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_0_ce0_local = 1'b1;
    end else begin
        M_e_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln57_reg_337 == 2'd0))) begin
        M_e_0_we0_local = 1'b1;
    end else begin
        M_e_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_1_ce0_local = 1'b1;
    end else begin
        M_e_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln57_reg_337 == 2'd1))) begin
        M_e_1_we0_local = 1'b1;
    end else begin
        M_e_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_2_ce0_local = 1'b1;
    end else begin
        M_e_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln57_reg_337 == 2'd2))) begin
        M_e_2_we0_local = 1'b1;
    end else begin
        M_e_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        M_e_3_ce0_local = 1'b1;
    end else begin
        M_e_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln57_reg_337 == 2'd3))) begin
        M_e_3_we0_local = 1'b1;
    end else begin
        M_e_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln56_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln56_reg_333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_e_0_address0 = zext_ln59_fu_287_p1;

assign M_e_0_ce0 = M_e_0_ce0_local;

assign M_e_0_d0 = A_dram_read;

assign M_e_0_we0 = M_e_0_we0_local;

assign M_e_1_address0 = zext_ln59_fu_287_p1;

assign M_e_1_ce0 = M_e_1_ce0_local;

assign M_e_1_d0 = A_dram_read;

assign M_e_1_we0 = M_e_1_we0_local;

assign M_e_2_address0 = zext_ln59_fu_287_p1;

assign M_e_2_ce0 = M_e_2_ce0_local;

assign M_e_2_d0 = A_dram_read;

assign M_e_2_we0 = M_e_2_we0_local;

assign M_e_3_address0 = zext_ln59_fu_287_p1;

assign M_e_3_ce0 = M_e_3_ce0_local;

assign M_e_3_d0 = A_dram_read;

assign M_e_3_we0 = M_e_3_we0_local;

assign add_ln56_1_fu_171_p2 = (indvar_flatten7_fu_74 + 62'd1);

assign add_ln56_fu_197_p2 = (r_fu_70 + 31'd1);

assign add_ln57_fu_271_p2 = (select_ln56_fu_203_p3 + 31'd1);

assign add_ln59_1_fu_231_p2 = (shl_ln59_fu_219_p2 + shl_ln59_1_fu_225_p2);

assign add_ln59_fu_255_p2 = (trunc_ln59_fu_237_p1 + lshr_ln1_fu_245_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln56_fu_166_p2 = ((indvar_flatten7_fu_74 == bound5) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_189_p2 = (($signed(zext_ln57_fu_185_p1) < $signed(cols)) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_245_p4 = {{select_ln56_fu_203_p3[16:2]}};

assign select_ln56_1_fu_211_p3 = ((icmp_ln57_fu_189_p2[0:0] == 1'b1) ? r_fu_70 : add_ln56_fu_197_p2);

assign select_ln56_fu_203_p3 = ((icmp_ln57_fu_189_p2[0:0] == 1'b1) ? c_1_fu_66 : 31'd0);

assign shl_ln59_1_fu_225_p2 = select_ln56_1_fu_211_p3 << 31'd4;

assign shl_ln59_fu_219_p2 = select_ln56_1_fu_211_p3 << 31'd6;

assign trunc_ln57_fu_241_p1 = select_ln56_fu_203_p3[1:0];

assign trunc_ln59_fu_237_p1 = add_ln59_1_fu_231_p2[14:0];

assign zext_ln57_fu_185_p1 = c_1_fu_66;

assign zext_ln59_fu_287_p1 = add_ln59_reg_341;

endmodule //fmm_reduce_kernel_load_matrix_from_dram_Pipeline_VITIS_LOOP_56_3_VITIS_LOOP_57_4
