// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_find_best_move (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        k1,
        k2,
        M_rows,
        M_t_i,
        M_t_o,
        M_t_o_ap_vld,
        M_cols,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_we0,
        M_e_0_d0,
        M_e_0_q0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_we0,
        M_e_1_d0,
        M_e_1_q0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_we0,
        M_e_2_d0,
        M_e_2_q0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_we0,
        M_e_3_d0,
        M_e_3_q0,
        M_t_capacity,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] k1;
input  [31:0] k2;
input  [31:0] M_rows;
input  [31:0] M_t_i;
output  [31:0] M_t_o;
output   M_t_o_ap_vld;
input  [31:0] M_cols;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
output   M_e_0_we0;
output  [31:0] M_e_0_d0;
input  [31:0] M_e_0_q0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
output   M_e_1_we0;
output  [31:0] M_e_1_d0;
input  [31:0] M_e_1_q0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
output   M_e_2_we0;
output  [31:0] M_e_2_d0;
input  [31:0] M_e_2_q0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
output   M_e_3_we0;
output  [31:0] M_e_3_d0;
input  [31:0] M_e_3_q0;
input  [31:0] M_t_capacity;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] M_t_o;
reg M_t_o_ap_vld;
reg[14:0] M_e_0_address0;
reg M_e_0_ce0;
reg M_e_0_we0;
reg[14:0] M_e_1_address0;
reg M_e_1_ce0;
reg M_e_1_we0;
reg[14:0] M_e_2_address0;
reg M_e_2_ce0;
reg M_e_2_we0;
reg[14:0] M_e_3_address0;
reg M_e_3_ce0;
reg M_e_3_we0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] R_fu_344_p2;
reg   [31:0] R_reg_741;
reg   [30:0] i_1_reg_747;
wire    ap_CS_fsm_state2;
wire   [31:0] zext_ln213_fu_383_p1;
reg   [31:0] zext_ln213_reg_753;
wire   [30:0] j_3_fu_392_p2;
reg   [30:0] j_3_reg_762;
wire   [31:0] zext_ln213_1_fu_398_p1;
wire   [0:0] icmp_ln213_1_fu_450_p2;
reg   [0:0] icmp_ln213_1_reg_772;
wire    ap_CS_fsm_state3;
reg   [31:0] out_sign_0_load_1_reg_779;
wire    ap_CS_fsm_state4;
reg   [0:0] write_flag9_0_load_1_reg_785;
reg   [31:0] out_r2_0_load_1_reg_791;
reg   [0:0] write_flag6_0_load_1_reg_797;
reg   [31:0] out_r1_0_load_1_reg_803;
reg   [0:0] write_flag3_0_load_1_reg_809;
reg   [31:0] agg_result_0_load_1_reg_815;
wire   [8:0] trunc_ln213_fu_458_p1;
reg   [8:0] trunc_ln213_reg_821;
reg   [31:0] n_reg_827;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln217_fu_485_p2;
reg   [0:0] icmp_ln217_reg_832;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_ap_return;
reg   [31:0] best_score_reg_836;
wire    ap_CS_fsm_state7;
wire   [31:0] select_ln219_fu_495_p3;
wire    ap_CS_fsm_state8;
wire   [0:0] or_ln219_fu_501_p2;
wire   [31:0] select_ln219_1_fu_506_p3;
wire   [0:0] or_ln219_1_fu_512_p2;
wire   [31:0] select_ln219_2_fu_517_p3;
wire   [0:0] or_ln219_2_fu_524_p2;
wire   [31:0] select_ln219_3_fu_529_p3;
wire   [31:0] select_ln219_4_fu_536_p3;
wire   [0:0] icmp_ln221_fu_551_p2;
reg   [0:0] icmp_ln221_reg_883;
reg   [31:0] best_score_1_reg_887;
wire    ap_CS_fsm_state10;
wire   [31:0] j_2_fu_625_p2;
wire    ap_CS_fsm_state11;
wire    grp_compute_pp_nn_fu_272_ap_start;
wire    grp_compute_pp_nn_fu_272_ap_done;
wire    grp_compute_pp_nn_fu_272_ap_idle;
wire    grp_compute_pp_nn_fu_272_ap_ready;
wire   [14:0] grp_compute_pp_nn_fu_272_M_e_0_address0;
wire    grp_compute_pp_nn_fu_272_M_e_0_ce0;
wire   [14:0] grp_compute_pp_nn_fu_272_M_e_1_address0;
wire    grp_compute_pp_nn_fu_272_M_e_1_ce0;
wire   [14:0] grp_compute_pp_nn_fu_272_M_e_2_address0;
wire    grp_compute_pp_nn_fu_272_M_e_2_ce0;
wire   [14:0] grp_compute_pp_nn_fu_272_M_e_3_address0;
wire    grp_compute_pp_nn_fu_272_M_e_3_ce0;
wire   [31:0] grp_compute_pp_nn_fu_272_ap_return_0;
wire   [31:0] grp_compute_pp_nn_fu_272_ap_return_1;
wire    grp_compute_greedy_potential_score_fu_288_ap_start;
wire    grp_compute_greedy_potential_score_fu_288_ap_done;
wire    grp_compute_greedy_potential_score_fu_288_ap_idle;
wire    grp_compute_greedy_potential_score_fu_288_ap_ready;
reg   [1:0] grp_compute_greedy_potential_score_fu_288_sign;
wire   [14:0] grp_compute_greedy_potential_score_fu_288_M_e_0_address0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_0_ce0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_0_we0;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_M_e_0_d0;
wire   [14:0] grp_compute_greedy_potential_score_fu_288_M_e_1_address0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_1_ce0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_1_we0;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_M_e_1_d0;
wire   [14:0] grp_compute_greedy_potential_score_fu_288_M_e_2_address0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_2_ce0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_2_we0;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_M_e_2_d0;
wire   [14:0] grp_compute_greedy_potential_score_fu_288_M_e_3_address0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_3_ce0;
wire    grp_compute_greedy_potential_score_fu_288_M_e_3_we0;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_M_e_3_d0;
wire   [31:0] grp_compute_greedy_potential_score_fu_288_M_t_o;
wire    grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld;
reg   [31:0] j_reg_102;
wire   [0:0] icmp_ln213_fu_387_p2;
reg   [31:0] agg_result_2_reg_112;
reg   [0:0] write_flag3_2_reg_122;
reg   [31:0] out_r1_2_reg_132;
reg   [0:0] write_flag6_2_reg_142;
reg   [31:0] out_r2_2_reg_152;
reg   [0:0] write_flag9_2_reg_162;
reg   [31:0] out_sign_2_reg_172;
reg   [31:0] empty_41_reg_182;
reg   [31:0] ap_phi_mux_agg_result_3_phi_fu_195_p4;
reg   [31:0] agg_result_3_reg_192;
wire    ap_CS_fsm_state9;
wire   [31:0] select_ln223_fu_562_p3;
reg   [0:0] ap_phi_mux_write_flag3_3_phi_fu_205_p4;
reg   [0:0] write_flag3_3_reg_202;
wire   [0:0] or_ln223_fu_570_p2;
reg   [31:0] ap_phi_mux_out_r1_3_phi_fu_215_p4;
reg   [31:0] out_r1_3_reg_212;
wire   [31:0] select_ln223_1_fu_577_p3;
reg   [0:0] ap_phi_mux_write_flag6_3_phi_fu_225_p4;
reg   [0:0] write_flag6_3_reg_222;
wire   [0:0] or_ln223_1_fu_585_p2;
reg   [31:0] ap_phi_mux_out_r2_3_phi_fu_235_p4;
reg   [31:0] out_r2_3_reg_232;
wire   [31:0] select_ln223_2_fu_592_p3;
reg   [0:0] ap_phi_mux_write_flag9_3_phi_fu_245_p4;
reg   [0:0] write_flag9_3_reg_242;
wire   [0:0] or_ln223_2_fu_601_p2;
reg   [31:0] ap_phi_mux_out_sign_3_phi_fu_255_p4;
reg   [31:0] out_sign_3_reg_252;
wire   [31:0] select_ln223_3_fu_608_p3;
reg   [31:0] ap_phi_mux_empty_42_phi_fu_265_p4;
reg   [31:0] empty_42_reg_262;
wire   [31:0] select_ln223_4_fu_617_p3;
reg    grp_compute_pp_nn_fu_272_ap_start_reg;
reg    grp_compute_greedy_potential_score_fu_288_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [30:0] i_fu_54;
reg   [31:0] empty_fu_58;
reg   [31:0] out_sign_0_fu_62;
reg   [0:0] write_flag9_0_fu_66;
reg   [31:0] out_r2_0_fu_70;
reg   [0:0] write_flag6_0_fu_74;
reg   [31:0] out_r1_0_fu_78;
reg   [0:0] write_flag3_0_fu_82;
reg   [31:0] agg_result_0_fu_86;
wire   [31:0] select_ln228_fu_402_p3;
wire   [31:0] select_ln228_1_fu_410_p3;
wire   [31:0] select_ln228_2_fu_418_p3;
wire   [30:0] tmp_fu_475_p4;
wire   [0:0] icmp_ln219_fu_491_p2;
wire   [30:0] tmp_4_fu_542_p4;
wire   [0:0] icmp_ln223_fu_557_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_compute_pp_nn_fu_272_ap_start_reg = 1'b0;
#0 grp_compute_greedy_potential_score_fu_288_ap_start_reg = 1'b0;
#0 i_fu_54 = 31'd0;
#0 empty_fu_58 = 32'd0;
#0 out_sign_0_fu_62 = 32'd0;
#0 write_flag9_0_fu_66 = 1'd0;
#0 out_r2_0_fu_70 = 32'd0;
#0 write_flag6_0_fu_74 = 1'd0;
#0 out_r1_0_fu_78 = 32'd0;
#0 write_flag3_0_fu_82 = 1'd0;
#0 agg_result_0_fu_86 = 32'd0;
end

fmm_reduce_kernel_compute_pp_nn grp_compute_pp_nn_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_pp_nn_fu_272_ap_start),
    .ap_done(grp_compute_pp_nn_fu_272_ap_done),
    .ap_idle(grp_compute_pp_nn_fu_272_ap_idle),
    .ap_ready(grp_compute_pp_nn_fu_272_ap_ready),
    .r1(i_1_reg_747),
    .r2(trunc_ln213_reg_821),
    .M_cols(M_cols),
    .M_e_0_address0(grp_compute_pp_nn_fu_272_M_e_0_address0),
    .M_e_0_ce0(grp_compute_pp_nn_fu_272_M_e_0_ce0),
    .M_e_0_q0(M_e_0_q0),
    .M_e_1_address0(grp_compute_pp_nn_fu_272_M_e_1_address0),
    .M_e_1_ce0(grp_compute_pp_nn_fu_272_M_e_1_ce0),
    .M_e_1_q0(M_e_1_q0),
    .M_e_2_address0(grp_compute_pp_nn_fu_272_M_e_2_address0),
    .M_e_2_ce0(grp_compute_pp_nn_fu_272_M_e_2_ce0),
    .M_e_2_q0(M_e_2_q0),
    .M_e_3_address0(grp_compute_pp_nn_fu_272_M_e_3_address0),
    .M_e_3_ce0(grp_compute_pp_nn_fu_272_M_e_3_ce0),
    .M_e_3_q0(M_e_3_q0),
    .ap_return_0(grp_compute_pp_nn_fu_272_ap_return_0),
    .ap_return_1(grp_compute_pp_nn_fu_272_ap_return_1)
);

fmm_reduce_kernel_compute_greedy_potential_score grp_compute_greedy_potential_score_fu_288(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_greedy_potential_score_fu_288_ap_start),
    .ap_done(grp_compute_greedy_potential_score_fu_288_ap_done),
    .ap_idle(grp_compute_greedy_potential_score_fu_288_ap_idle),
    .ap_ready(grp_compute_greedy_potential_score_fu_288_ap_ready),
    .r1(i_1_reg_747),
    .r2(trunc_ln213_reg_821),
    .sign(grp_compute_greedy_potential_score_fu_288_sign),
    .k1(k1),
    .k2(k2),
    .M_cols(M_cols),
    .M_e_0_address0(grp_compute_greedy_potential_score_fu_288_M_e_0_address0),
    .M_e_0_ce0(grp_compute_greedy_potential_score_fu_288_M_e_0_ce0),
    .M_e_0_we0(grp_compute_greedy_potential_score_fu_288_M_e_0_we0),
    .M_e_0_d0(grp_compute_greedy_potential_score_fu_288_M_e_0_d0),
    .M_e_0_q0(M_e_0_q0),
    .M_e_1_address0(grp_compute_greedy_potential_score_fu_288_M_e_1_address0),
    .M_e_1_ce0(grp_compute_greedy_potential_score_fu_288_M_e_1_ce0),
    .M_e_1_we0(grp_compute_greedy_potential_score_fu_288_M_e_1_we0),
    .M_e_1_d0(grp_compute_greedy_potential_score_fu_288_M_e_1_d0),
    .M_e_1_q0(M_e_1_q0),
    .M_e_2_address0(grp_compute_greedy_potential_score_fu_288_M_e_2_address0),
    .M_e_2_ce0(grp_compute_greedy_potential_score_fu_288_M_e_2_ce0),
    .M_e_2_we0(grp_compute_greedy_potential_score_fu_288_M_e_2_we0),
    .M_e_2_d0(grp_compute_greedy_potential_score_fu_288_M_e_2_d0),
    .M_e_2_q0(M_e_2_q0),
    .M_e_3_address0(grp_compute_greedy_potential_score_fu_288_M_e_3_address0),
    .M_e_3_ce0(grp_compute_greedy_potential_score_fu_288_M_e_3_ce0),
    .M_e_3_we0(grp_compute_greedy_potential_score_fu_288_M_e_3_we0),
    .M_e_3_d0(grp_compute_greedy_potential_score_fu_288_M_e_3_d0),
    .M_e_3_q0(M_e_3_q0),
    .M_t_i(M_t_i),
    .M_t_o(grp_compute_greedy_potential_score_fu_288_M_t_o),
    .M_t_o_ap_vld(grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld),
    .M_t_capacity(M_t_capacity),
    .M_rows(M_rows),
    .ap_return(grp_compute_greedy_potential_score_fu_288_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_greedy_potential_score_fu_288_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd1)))) begin
            grp_compute_greedy_potential_score_fu_288_ap_start_reg <= 1'b1;
        end else if ((grp_compute_greedy_potential_score_fu_288_ap_ready == 1'b1)) begin
            grp_compute_greedy_potential_score_fu_288_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_pp_nn_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln213_1_reg_772 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_compute_pp_nn_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_compute_pp_nn_fu_272_ap_ready == 1'b1)) begin
            grp_compute_pp_nn_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        agg_result_0_fu_86 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        agg_result_0_fu_86 <= ap_phi_mux_agg_result_3_phi_fu_195_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        agg_result_2_reg_112 <= select_ln219_fu_495_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        agg_result_2_reg_112 <= agg_result_0_load_1_reg_815;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        agg_result_3_reg_192 <= select_ln223_fu_562_p3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        agg_result_3_reg_192 <= agg_result_2_reg_112;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        empty_41_reg_182 <= select_ln219_4_fu_536_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        empty_41_reg_182 <= empty_fu_58;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        empty_42_reg_262 <= select_ln223_4_fu_617_p3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        empty_42_reg_262 <= empty_41_reg_182;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        empty_fu_58 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_fu_58 <= ap_phi_mux_empty_42_phi_fu_265_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_54 <= 31'd0;
    end else if (((icmp_ln213_1_reg_772 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_54 <= j_3_reg_762;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        j_reg_102 <= j_2_fu_625_p2;
    end else if (((icmp_ln213_fu_387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_102 <= zext_ln213_1_fu_398_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        out_r1_2_reg_132 <= select_ln219_1_fu_506_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        out_r1_2_reg_132 <= out_r1_0_load_1_reg_803;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        out_r1_3_reg_212 <= select_ln223_1_fu_577_p3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        out_r1_3_reg_212 <= out_r1_2_reg_132;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        out_r2_2_reg_152 <= select_ln219_2_fu_517_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        out_r2_2_reg_152 <= out_r2_0_load_1_reg_791;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        out_r2_3_reg_232 <= select_ln223_2_fu_592_p3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        out_r2_3_reg_232 <= out_r2_2_reg_152;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        out_sign_2_reg_172 <= select_ln219_3_fu_529_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        out_sign_2_reg_172 <= out_sign_0_load_1_reg_779;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        out_sign_3_reg_252 <= select_ln223_3_fu_608_p3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        out_sign_3_reg_252 <= out_sign_2_reg_172;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_flag3_0_fu_82 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        write_flag3_0_fu_82 <= ap_phi_mux_write_flag3_3_phi_fu_205_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        write_flag3_2_reg_122 <= or_ln219_fu_501_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        write_flag3_2_reg_122 <= write_flag3_0_load_1_reg_809;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        write_flag3_3_reg_202 <= or_ln223_fu_570_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        write_flag3_3_reg_202 <= write_flag3_2_reg_122;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_flag6_0_fu_74 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        write_flag6_0_fu_74 <= ap_phi_mux_write_flag6_3_phi_fu_225_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        write_flag6_2_reg_142 <= or_ln219_1_fu_512_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        write_flag6_2_reg_142 <= write_flag6_0_load_1_reg_797;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        write_flag6_3_reg_222 <= or_ln223_1_fu_585_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        write_flag6_3_reg_222 <= write_flag6_2_reg_142;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_flag9_0_fu_66 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        write_flag9_0_fu_66 <= ap_phi_mux_write_flag9_3_phi_fu_245_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln217_reg_832 == 1'd1))) begin
        write_flag9_2_reg_162 <= or_ln219_2_fu_524_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
        write_flag9_2_reg_162 <= write_flag9_0_load_1_reg_785;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        write_flag9_3_reg_242 <= or_ln223_2_fu_601_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
        write_flag9_3_reg_242 <= write_flag9_2_reg_162;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        R_reg_741 <= R_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        agg_result_0_load_1_reg_815 <= agg_result_0_fu_86;
        out_r1_0_load_1_reg_803 <= out_r1_0_fu_78;
        out_r2_0_load_1_reg_791 <= out_r2_0_fu_70;
        out_sign_0_load_1_reg_779 <= out_sign_0_fu_62;
        trunc_ln213_reg_821 <= trunc_ln213_fu_458_p1;
        write_flag3_0_load_1_reg_809 <= write_flag3_0_fu_82;
        write_flag6_0_load_1_reg_797 <= write_flag6_0_fu_74;
        write_flag9_0_load_1_reg_785 <= write_flag9_0_fu_66;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        best_score_1_reg_887 <= grp_compute_greedy_potential_score_fu_288_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        best_score_reg_836 <= grp_compute_greedy_potential_score_fu_288_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_747 <= i_fu_54;
        j_3_reg_762 <= j_3_fu_392_p2;
        zext_ln213_reg_753[30 : 0] <= zext_ln213_fu_383_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln213_1_reg_772 <= icmp_ln213_1_fu_450_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln217_reg_832 <= icmp_ln217_fu_485_p2;
        n_reg_827 <= grp_compute_pp_nn_fu_272_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        icmp_ln221_reg_883 <= icmp_ln221_fu_551_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        out_r1_0_fu_78 <= ap_phi_mux_out_r1_3_phi_fu_215_p4;
        out_r2_0_fu_70 <= ap_phi_mux_out_r2_3_phi_fu_235_p4;
        out_sign_0_fu_62 <= ap_phi_mux_out_sign_3_phi_fu_255_p4;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_0_address0 = grp_compute_greedy_potential_score_fu_288_M_e_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_0_address0 = grp_compute_pp_nn_fu_272_M_e_0_address0;
    end else begin
        M_e_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_0_ce0 = grp_compute_greedy_potential_score_fu_288_M_e_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_0_ce0 = grp_compute_pp_nn_fu_272_M_e_0_ce0;
    end else begin
        M_e_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_0_we0 = grp_compute_greedy_potential_score_fu_288_M_e_0_we0;
    end else begin
        M_e_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_1_address0 = grp_compute_greedy_potential_score_fu_288_M_e_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_1_address0 = grp_compute_pp_nn_fu_272_M_e_1_address0;
    end else begin
        M_e_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_1_ce0 = grp_compute_greedy_potential_score_fu_288_M_e_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_1_ce0 = grp_compute_pp_nn_fu_272_M_e_1_ce0;
    end else begin
        M_e_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_1_we0 = grp_compute_greedy_potential_score_fu_288_M_e_1_we0;
    end else begin
        M_e_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_2_address0 = grp_compute_greedy_potential_score_fu_288_M_e_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_2_address0 = grp_compute_pp_nn_fu_272_M_e_2_address0;
    end else begin
        M_e_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_2_ce0 = grp_compute_greedy_potential_score_fu_288_M_e_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_2_ce0 = grp_compute_pp_nn_fu_272_M_e_2_ce0;
    end else begin
        M_e_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_2_we0 = grp_compute_greedy_potential_score_fu_288_M_e_2_we0;
    end else begin
        M_e_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_3_address0 = grp_compute_greedy_potential_score_fu_288_M_e_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_3_address0 = grp_compute_pp_nn_fu_272_M_e_3_address0;
    end else begin
        M_e_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_3_ce0 = grp_compute_greedy_potential_score_fu_288_M_e_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        M_e_3_ce0 = grp_compute_pp_nn_fu_272_M_e_3_ce0;
    end else begin
        M_e_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_e_3_we0 = grp_compute_greedy_potential_score_fu_288_M_e_3_we0;
    end else begin
        M_e_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        M_t_o = grp_compute_greedy_potential_score_fu_288_M_t_o;
    end else begin
        M_t_o = M_t_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        M_t_o_ap_vld = grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld;
    end else begin
        M_t_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_greedy_potential_score_fu_288_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_pp_nn_fu_272_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_greedy_potential_score_fu_288_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln213_fu_387_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_agg_result_3_phi_fu_195_p4 = select_ln223_fu_562_p3;
    end else begin
        ap_phi_mux_agg_result_3_phi_fu_195_p4 = agg_result_3_reg_192;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_empty_42_phi_fu_265_p4 = select_ln223_4_fu_617_p3;
    end else begin
        ap_phi_mux_empty_42_phi_fu_265_p4 = empty_42_reg_262;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_out_r1_3_phi_fu_215_p4 = select_ln223_1_fu_577_p3;
    end else begin
        ap_phi_mux_out_r1_3_phi_fu_215_p4 = out_r1_3_reg_212;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_out_r2_3_phi_fu_235_p4 = select_ln223_2_fu_592_p3;
    end else begin
        ap_phi_mux_out_r2_3_phi_fu_235_p4 = out_r2_3_reg_232;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_out_sign_3_phi_fu_255_p4 = select_ln223_3_fu_608_p3;
    end else begin
        ap_phi_mux_out_sign_3_phi_fu_255_p4 = out_sign_3_reg_252;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_write_flag3_3_phi_fu_205_p4 = or_ln223_fu_570_p2;
    end else begin
        ap_phi_mux_write_flag3_3_phi_fu_205_p4 = write_flag3_3_reg_202;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_write_flag6_3_phi_fu_225_p4 = or_ln223_1_fu_585_p2;
    end else begin
        ap_phi_mux_write_flag6_3_phi_fu_225_p4 = write_flag6_3_reg_222;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln221_reg_883 == 1'd1))) begin
        ap_phi_mux_write_flag9_3_phi_fu_245_p4 = or_ln223_2_fu_601_p2;
    end else begin
        ap_phi_mux_write_flag9_3_phi_fu_245_p4 = write_flag9_3_reg_242;
    end
end

always @ (*) begin
    if (((icmp_ln213_fu_387_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_compute_greedy_potential_score_fu_288_sign = 2'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_compute_greedy_potential_score_fu_288_sign = 2'd1;
    end else begin
        grp_compute_greedy_potential_score_fu_288_sign = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln213_fu_387_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln213_1_reg_772 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b1 == ap_CS_fsm_state5) & (grp_compute_pp_nn_fu_272_ap_done == 1'b1) & (icmp_ln217_fu_485_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_compute_greedy_potential_score_fu_288_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln221_reg_883 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_compute_greedy_potential_score_fu_288_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_e_0_d0 = grp_compute_greedy_potential_score_fu_288_M_e_0_d0;

assign M_e_1_d0 = grp_compute_greedy_potential_score_fu_288_M_e_1_d0;

assign M_e_2_d0 = grp_compute_greedy_potential_score_fu_288_M_e_2_d0;

assign M_e_3_d0 = grp_compute_greedy_potential_score_fu_288_M_e_3_d0;

assign R_fu_344_p2 = (M_t_i + M_rows);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = agg_result_0_fu_86;

assign ap_return_1 = select_ln228_fu_402_p3;

assign ap_return_2 = select_ln228_1_fu_410_p3;

assign ap_return_3 = select_ln228_2_fu_418_p3;

assign grp_compute_greedy_potential_score_fu_288_ap_start = grp_compute_greedy_potential_score_fu_288_ap_start_reg;

assign grp_compute_pp_nn_fu_272_ap_start = grp_compute_pp_nn_fu_272_ap_start_reg;

assign icmp_ln213_1_fu_450_p2 = ((j_reg_102 == R_reg_741) ? 1'b1 : 1'b0);

assign icmp_ln213_fu_387_p2 = (($signed(zext_ln213_fu_383_p1) < $signed(R_reg_741)) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_485_p2 = (($signed(tmp_fu_475_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln219_fu_491_p2 = (($signed(best_score_reg_836) > $signed(empty_fu_58)) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_551_p2 = (($signed(tmp_4_fu_542_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_557_p2 = (($signed(best_score_1_reg_887) > $signed(empty_41_reg_182)) ? 1'b1 : 1'b0);

assign j_2_fu_625_p2 = (j_reg_102 + 32'd1);

assign j_3_fu_392_p2 = (i_fu_54 + 31'd1);

assign or_ln219_1_fu_512_p2 = (write_flag6_0_load_1_reg_797 | icmp_ln219_fu_491_p2);

assign or_ln219_2_fu_524_p2 = (write_flag9_0_load_1_reg_785 | icmp_ln219_fu_491_p2);

assign or_ln219_fu_501_p2 = (write_flag3_0_load_1_reg_809 | icmp_ln219_fu_491_p2);

assign or_ln223_1_fu_585_p2 = (write_flag6_2_reg_142 | icmp_ln223_fu_557_p2);

assign or_ln223_2_fu_601_p2 = (write_flag9_2_reg_162 | icmp_ln223_fu_557_p2);

assign or_ln223_fu_570_p2 = (write_flag3_2_reg_122 | icmp_ln223_fu_557_p2);

assign select_ln219_1_fu_506_p3 = ((icmp_ln219_fu_491_p2[0:0] == 1'b1) ? zext_ln213_reg_753 : out_r1_0_load_1_reg_803);

assign select_ln219_2_fu_517_p3 = ((icmp_ln219_fu_491_p2[0:0] == 1'b1) ? j_reg_102 : out_r2_0_load_1_reg_791);

assign select_ln219_3_fu_529_p3 = ((icmp_ln219_fu_491_p2[0:0] == 1'b1) ? 32'd1 : out_sign_0_load_1_reg_779);

assign select_ln219_4_fu_536_p3 = ((icmp_ln219_fu_491_p2[0:0] == 1'b1) ? best_score_reg_836 : empty_fu_58);

assign select_ln219_fu_495_p3 = ((icmp_ln219_fu_491_p2[0:0] == 1'b1) ? best_score_reg_836 : agg_result_0_load_1_reg_815);

assign select_ln223_1_fu_577_p3 = ((icmp_ln223_fu_557_p2[0:0] == 1'b1) ? zext_ln213_reg_753 : out_r1_2_reg_132);

assign select_ln223_2_fu_592_p3 = ((icmp_ln223_fu_557_p2[0:0] == 1'b1) ? j_reg_102 : out_r2_2_reg_152);

assign select_ln223_3_fu_608_p3 = ((icmp_ln223_fu_557_p2[0:0] == 1'b1) ? 32'd4294967295 : out_sign_2_reg_172);

assign select_ln223_4_fu_617_p3 = ((icmp_ln223_fu_557_p2[0:0] == 1'b1) ? best_score_1_reg_887 : empty_41_reg_182);

assign select_ln223_fu_562_p3 = ((icmp_ln223_fu_557_p2[0:0] == 1'b1) ? best_score_1_reg_887 : agg_result_2_reg_112);

assign select_ln228_1_fu_410_p3 = ((write_flag6_0_fu_74[0:0] == 1'b1) ? out_r2_0_fu_70 : 32'd0);

assign select_ln228_2_fu_418_p3 = ((write_flag9_0_fu_66[0:0] == 1'b1) ? out_sign_0_fu_62 : 32'd0);

assign select_ln228_fu_402_p3 = ((write_flag3_0_fu_82[0:0] == 1'b1) ? out_r1_0_fu_78 : 32'd0);

assign tmp_4_fu_542_p4 = {{n_reg_827[31:1]}};

assign tmp_fu_475_p4 = {{grp_compute_pp_nn_fu_272_ap_return_0[31:1]}};

assign trunc_ln213_fu_458_p1 = j_reg_102[8:0];

assign zext_ln213_1_fu_398_p1 = j_3_fu_392_p2;

assign zext_ln213_fu_383_p1 = i_fu_54;

always @ (posedge ap_clk) begin
    zext_ln213_reg_753[31] <= 1'b0;
end

endmodule //fmm_reduce_kernel_find_best_move
