// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln152,
        zext_ln144,
        add_ln144,
        sext_ln152,
        move_type_1_out,
        move_type_1_out_ap_vld,
        row2_1_out,
        row2_1_out_ap_vld,
        M_e_0_address0,
        M_e_0_ce0,
        M_e_0_q0,
        M_e_1_address0,
        M_e_1_ce0,
        M_e_1_q0,
        M_e_2_address0,
        M_e_2_ce0,
        M_e_2_q0,
        M_e_3_address0,
        M_e_3_ce0,
        M_e_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] zext_ln152;
input  [14:0] zext_ln144;
input  [1:0] add_ln144;
input  [31:0] sext_ln152;
output  [31:0] move_type_1_out;
output   move_type_1_out_ap_vld;
output  [31:0] row2_1_out;
output   row2_1_out_ap_vld;
output  [14:0] M_e_0_address0;
output   M_e_0_ce0;
input  [31:0] M_e_0_q0;
output  [14:0] M_e_1_address0;
output   M_e_1_ce0;
input  [31:0] M_e_1_q0;
output  [14:0] M_e_2_address0;
output   M_e_2_ce0;
input  [31:0] M_e_2_q0;
output  [14:0] M_e_3_address0;
output   M_e_3_ce0;
input  [31:0] M_e_3_q0;

reg ap_idle;
reg move_type_1_out_ap_vld;
reg row2_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] or_cond44_fu_316_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] trunc_ln155_fu_248_p1;
reg   [31:0] trunc_ln155_reg_381;
wire   [33:0] add_ln152_fu_252_p2;
reg   [33:0] add_ln152_reg_386;
wire   [0:0] icmp_ln152_fu_258_p2;
reg   [0:0] icmp_ln152_reg_391;
wire   [63:0] zext_ln154_fu_240_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] move_type_fu_76;
wire   [31:0] move_type_3_fu_299_p3;
wire    ap_loop_init;
reg   [31:0] row2_fu_80;
wire   [31:0] row2_3_fu_308_p3;
reg   [33:0] r_fu_84;
wire   [33:0] zext_ln152_cast_fu_182_p1;
reg   [33:0] ap_sig_allocacmp_r_1;
wire    ap_block_pp0_stage0_01001;
reg    M_e_0_ce0_local;
reg    M_e_1_ce0_local;
reg    M_e_2_ce0_local;
reg    M_e_3_ce0_local;
wire   [8:0] trunc_ln154_fu_204_p1;
wire   [10:0] trunc_ln154_1_fu_216_p1;
wire   [14:0] p_shl_fu_208_p3;
wire   [14:0] p_shl4_fu_220_p3;
wire   [14:0] add_ln154_1_fu_228_p2;
wire   [14:0] add_ln154_fu_234_p2;
wire  signed [33:0] sext_ln152_cast_fu_178_p1;
wire   [31:0] v_fu_270_p9;
wire   [31:0] v_fu_270_p11;
wire   [0:0] icmp_ln155_fu_293_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] v_fu_270_p1;
wire  signed [1:0] v_fu_270_p3;
wire  signed [1:0] v_fu_270_p5;
wire   [1:0] v_fu_270_p7;
wire    ap_ce_reg;


(* dissolve_hierarchy = "yes" *) fmm_reduce_kernel_sparsemux_9_2_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_x_U71(
    .din0(M_e_0_q0),
    .din1(M_e_1_q0),
    .din2(M_e_2_q0),
    .din3(M_e_3_q0),
    .def(v_fu_270_p9),
    .sel(add_ln144),
    .dout(v_fu_270_p11)
);

fmm_reduce_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        move_type_fu_76 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) &
                  (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            move_type_fu_76 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            move_type_fu_76 <= move_type_3_fu_299_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        r_fu_84 <= 34'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) &
                  (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_84 <= zext_ln152_cast_fu_182_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            r_fu_84 <= add_ln152_reg_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        row2_fu_80 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) &
                  (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            row2_fu_80 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            row2_fu_80 <= row2_3_fu_308_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln152_reg_386   <= 34'd0;
        icmp_ln152_reg_391 <= 1'b0;
        trunc_ln155_reg_381 <= 32'd0;
    end
    else if (((1'b0 == ap_block_pp0_stage0_11001) &
              (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln152_reg_386   <= add_ln152_fu_252_p2;
        icmp_ln152_reg_391 <= icmp_ln152_fu_258_p2;
        trunc_ln155_reg_381 <= trunc_ln155_fu_248_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_0_ce0_local = 1'b1;
    end else begin
        M_e_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_1_ce0_local = 1'b1;
    end else begin
        M_e_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_2_ce0_local = 1'b1;
    end else begin
        M_e_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_3_ce0_local = 1'b1;
    end else begin
        M_e_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond44_fu_316_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_r_1 = zext_ln152_cast_fu_182_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_r_1 = add_ln152_reg_386;
        end else begin
            ap_sig_allocacmp_r_1 = r_fu_84;
        end
    end else begin
        ap_sig_allocacmp_r_1 = r_fu_84;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond44_fu_316_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        move_type_1_out_ap_vld = 1'b1;
    end else begin
        move_type_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond44_fu_316_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row2_1_out_ap_vld = 1'b1;
    end else begin
        row2_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_e_0_address0 = zext_ln154_fu_240_p1;

assign M_e_0_ce0 = M_e_0_ce0_local;

assign M_e_1_address0 = zext_ln154_fu_240_p1;

assign M_e_1_ce0 = M_e_1_ce0_local;

assign M_e_2_address0 = zext_ln154_fu_240_p1;

assign M_e_2_ce0 = M_e_2_ce0_local;

assign M_e_3_address0 = zext_ln154_fu_240_p1;

assign M_e_3_ce0 = M_e_3_ce0_local;

assign add_ln152_fu_252_p2 = ($signed(ap_sig_allocacmp_r_1) + $signed(34'd17179869183));

assign add_ln154_1_fu_228_p2 = (p_shl_fu_208_p3 + p_shl4_fu_220_p3);

assign add_ln154_fu_234_p2 = (add_ln154_1_fu_228_p2 + zext_ln144);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln152_fu_258_p2 = (($signed(add_ln152_fu_252_p2) > $signed(sext_ln152_cast_fu_178_p1)) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_293_p2 = ((v_fu_270_p11 == 32'd0) ? 1'b1 : 1'b0);

assign move_type_1_out = ((icmp_ln155_fu_293_p2[0:0] == 1'b1) ? move_type_fu_76 : v_fu_270_p11);

assign move_type_3_fu_299_p3 = ((icmp_ln155_fu_293_p2[0:0] == 1'b1) ? move_type_fu_76 : v_fu_270_p11);

assign or_cond44_fu_316_p2 = (icmp_ln155_fu_293_p2 & icmp_ln152_reg_391);

assign p_shl4_fu_220_p3 = {{trunc_ln154_1_fu_216_p1}, {4'd0}};

assign p_shl_fu_208_p3 = {{trunc_ln154_fu_204_p1}, {6'd0}};

assign row2_1_out = ((icmp_ln155_fu_293_p2[0:0] == 1'b1) ? row2_fu_80 : trunc_ln155_reg_381);

assign row2_3_fu_308_p3 = ((icmp_ln155_fu_293_p2[0:0] == 1'b1) ? row2_fu_80 : trunc_ln155_reg_381);

assign sext_ln152_cast_fu_178_p1 = $signed(sext_ln152);

assign trunc_ln154_1_fu_216_p1 = ap_sig_allocacmp_r_1[10:0];

assign trunc_ln154_fu_204_p1 = ap_sig_allocacmp_r_1[8:0];

assign trunc_ln155_fu_248_p1 = ap_sig_allocacmp_r_1[31:0];

assign v_fu_270_p9 = 'bx;

assign zext_ln152_cast_fu_182_p1 = zext_ln152;

assign zext_ln154_fu_240_p1 = add_ln154_fu_234_p2;

endmodule //fmm_reduce_kernel_compute_greedy_potential_score_Pipeline_VITIS_LOOP_152_2
