-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmm_reduce_kernel_find_best_move is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    k1 : IN STD_LOGIC_VECTOR (31 downto 0);
    k2 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_rows : IN STD_LOGIC_VECTOR (31 downto 0);
    M_t_i : IN STD_LOGIC_VECTOR (31 downto 0);
    M_t_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_t_o_ap_vld : OUT STD_LOGIC;
    M_cols : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_0_ce0 : OUT STD_LOGIC;
    M_e_0_we0 : OUT STD_LOGIC;
    M_e_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_1_ce0 : OUT STD_LOGIC;
    M_e_1_we0 : OUT STD_LOGIC;
    M_e_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_2_ce0 : OUT STD_LOGIC;
    M_e_2_we0 : OUT STD_LOGIC;
    M_e_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_e_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    M_e_3_ce0 : OUT STD_LOGIC;
    M_e_3_we0 : OUT STD_LOGIC;
    M_e_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    M_t_capacity : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fmm_reduce_kernel_find_best_move is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal R_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal R_reg_741 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_1_reg_747 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln213_fu_383_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln213_reg_753 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_3_fu_392_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal j_3_reg_762 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln213_1_fu_398_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln213_1_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln213_1_reg_772 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal out_sign_0_load_1_reg_779 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal write_flag9_0_load_1_reg_785 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r2_0_load_1_reg_791 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_flag6_0_load_1_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r1_0_load_1_reg_803 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_flag3_0_load_1_reg_809 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_0_load_1_reg_815 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln213_fu_458_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln213_reg_821 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_827 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln217_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln217_reg_832 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal best_score_reg_836 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal select_ln219_fu_495_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal or_ln219_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln219_1_fu_506_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln219_1_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln219_2_fu_517_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln219_2_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln219_3_fu_529_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln219_4_fu_536_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln221_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_883 : STD_LOGIC_VECTOR (0 downto 0);
    signal best_score_1_reg_887 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal j_2_fu_625_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_compute_pp_nn_fu_272_ap_start : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_ap_done : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_ap_idle : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_ap_ready : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_M_e_0_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_pp_nn_fu_272_M_e_0_ce0 : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_M_e_1_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_pp_nn_fu_272_M_e_1_ce0 : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_M_e_2_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_pp_nn_fu_272_M_e_2_ce0 : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_M_e_3_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_pp_nn_fu_272_M_e_3_ce0 : STD_LOGIC;
    signal grp_compute_pp_nn_fu_272_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_pp_nn_fu_272_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_ap_start : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_ap_done : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_ap_idle : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_ap_ready : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_sign : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_0_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_0_ce0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_0_we0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_1_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_1_ce0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_1_we0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_2_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_2_ce0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_2_we0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_3_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_e_3_ce0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_3_we0 : STD_LOGIC;
    signal grp_compute_greedy_potential_score_fu_288_M_e_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_t_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld : STD_LOGIC;
    signal j_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln213_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_2_reg_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_flag3_2_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r1_2_reg_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_flag6_2_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r2_2_reg_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal write_flag9_2_reg_162 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_sign_2_reg_172 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_25_reg_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_agg_result_3_phi_fu_195_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal agg_result_3_reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal select_ln223_fu_562_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_write_flag3_3_phi_fu_205_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag3_3_reg_202 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln223_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_out_r1_3_phi_fu_215_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r1_3_reg_212 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln223_1_fu_577_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_write_flag6_3_phi_fu_225_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag6_3_reg_222 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln223_1_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_out_r2_3_phi_fu_235_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r2_3_reg_232 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln223_2_fu_592_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_write_flag9_3_phi_fu_245_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag9_3_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln223_2_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_out_sign_3_phi_fu_255_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_sign_3_reg_252 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln223_3_fu_608_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_empty_26_phi_fu_265_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_26_reg_262 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln223_4_fu_617_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_pp_nn_fu_272_ap_start_reg : STD_LOGIC := '0';
    signal grp_compute_greedy_potential_score_fu_288_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal i_fu_54 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal empty_fu_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_sign_0_fu_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal write_flag9_0_fu_66 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_r2_0_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal write_flag6_0_fu_74 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_r1_0_fu_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal write_flag3_0_fu_82 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal agg_result_0_fu_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln228_fu_402_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln228_1_fu_410_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln228_2_fu_418_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_475_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln219_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_542_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln223_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fmm_reduce_kernel_compute_pp_nn IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        r1 : IN STD_LOGIC_VECTOR (30 downto 0);
        r2 : IN STD_LOGIC_VECTOR (8 downto 0);
        M_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_0_ce0 : OUT STD_LOGIC;
        M_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_1_ce0 : OUT STD_LOGIC;
        M_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_2_ce0 : OUT STD_LOGIC;
        M_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_3_ce0 : OUT STD_LOGIC;
        M_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fmm_reduce_kernel_compute_greedy_potential_score IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        r1 : IN STD_LOGIC_VECTOR (30 downto 0);
        r2 : IN STD_LOGIC_VECTOR (8 downto 0);
        sign : IN STD_LOGIC_VECTOR (1 downto 0);
        k1 : IN STD_LOGIC_VECTOR (31 downto 0);
        k2 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_0_ce0 : OUT STD_LOGIC;
        M_e_0_we0 : OUT STD_LOGIC;
        M_e_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_1_ce0 : OUT STD_LOGIC;
        M_e_1_we0 : OUT STD_LOGIC;
        M_e_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_2_ce0 : OUT STD_LOGIC;
        M_e_2_we0 : OUT STD_LOGIC;
        M_e_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_e_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        M_e_3_ce0 : OUT STD_LOGIC;
        M_e_3_we0 : OUT STD_LOGIC;
        M_e_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        M_t_i : IN STD_LOGIC_VECTOR (31 downto 0);
        M_t_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_t_o_ap_vld : OUT STD_LOGIC;
        M_t_capacity : IN STD_LOGIC_VECTOR (31 downto 0);
        M_rows : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_compute_pp_nn_fu_272 : component fmm_reduce_kernel_compute_pp_nn
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_pp_nn_fu_272_ap_start,
        ap_done => grp_compute_pp_nn_fu_272_ap_done,
        ap_idle => grp_compute_pp_nn_fu_272_ap_idle,
        ap_ready => grp_compute_pp_nn_fu_272_ap_ready,
        r1 => i_1_reg_747,
        r2 => trunc_ln213_reg_821,
        M_cols => M_cols,
        M_e_0_address0 => grp_compute_pp_nn_fu_272_M_e_0_address0,
        M_e_0_ce0 => grp_compute_pp_nn_fu_272_M_e_0_ce0,
        M_e_0_q0 => M_e_0_q0,
        M_e_1_address0 => grp_compute_pp_nn_fu_272_M_e_1_address0,
        M_e_1_ce0 => grp_compute_pp_nn_fu_272_M_e_1_ce0,
        M_e_1_q0 => M_e_1_q0,
        M_e_2_address0 => grp_compute_pp_nn_fu_272_M_e_2_address0,
        M_e_2_ce0 => grp_compute_pp_nn_fu_272_M_e_2_ce0,
        M_e_2_q0 => M_e_2_q0,
        M_e_3_address0 => grp_compute_pp_nn_fu_272_M_e_3_address0,
        M_e_3_ce0 => grp_compute_pp_nn_fu_272_M_e_3_ce0,
        M_e_3_q0 => M_e_3_q0,
        ap_return_0 => grp_compute_pp_nn_fu_272_ap_return_0,
        ap_return_1 => grp_compute_pp_nn_fu_272_ap_return_1);

    grp_compute_greedy_potential_score_fu_288 : component fmm_reduce_kernel_compute_greedy_potential_score
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_greedy_potential_score_fu_288_ap_start,
        ap_done => grp_compute_greedy_potential_score_fu_288_ap_done,
        ap_idle => grp_compute_greedy_potential_score_fu_288_ap_idle,
        ap_ready => grp_compute_greedy_potential_score_fu_288_ap_ready,
        r1 => i_1_reg_747,
        r2 => trunc_ln213_reg_821,
        sign => grp_compute_greedy_potential_score_fu_288_sign,
        k1 => k1,
        k2 => k2,
        M_cols => M_cols,
        M_e_0_address0 => grp_compute_greedy_potential_score_fu_288_M_e_0_address0,
        M_e_0_ce0 => grp_compute_greedy_potential_score_fu_288_M_e_0_ce0,
        M_e_0_we0 => grp_compute_greedy_potential_score_fu_288_M_e_0_we0,
        M_e_0_d0 => grp_compute_greedy_potential_score_fu_288_M_e_0_d0,
        M_e_0_q0 => M_e_0_q0,
        M_e_1_address0 => grp_compute_greedy_potential_score_fu_288_M_e_1_address0,
        M_e_1_ce0 => grp_compute_greedy_potential_score_fu_288_M_e_1_ce0,
        M_e_1_we0 => grp_compute_greedy_potential_score_fu_288_M_e_1_we0,
        M_e_1_d0 => grp_compute_greedy_potential_score_fu_288_M_e_1_d0,
        M_e_1_q0 => M_e_1_q0,
        M_e_2_address0 => grp_compute_greedy_potential_score_fu_288_M_e_2_address0,
        M_e_2_ce0 => grp_compute_greedy_potential_score_fu_288_M_e_2_ce0,
        M_e_2_we0 => grp_compute_greedy_potential_score_fu_288_M_e_2_we0,
        M_e_2_d0 => grp_compute_greedy_potential_score_fu_288_M_e_2_d0,
        M_e_2_q0 => M_e_2_q0,
        M_e_3_address0 => grp_compute_greedy_potential_score_fu_288_M_e_3_address0,
        M_e_3_ce0 => grp_compute_greedy_potential_score_fu_288_M_e_3_ce0,
        M_e_3_we0 => grp_compute_greedy_potential_score_fu_288_M_e_3_we0,
        M_e_3_d0 => grp_compute_greedy_potential_score_fu_288_M_e_3_d0,
        M_e_3_q0 => M_e_3_q0,
        M_t_i => M_t_i,
        M_t_o => grp_compute_greedy_potential_score_fu_288_M_t_o,
        M_t_o_ap_vld => grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld,
        M_t_capacity => M_t_capacity,
        M_rows => M_rows,
        ap_return => grp_compute_greedy_potential_score_fu_288_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_greedy_potential_score_fu_288_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_greedy_potential_score_fu_288_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_1)))) then 
                    grp_compute_greedy_potential_score_fu_288_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_greedy_potential_score_fu_288_ap_ready = ap_const_logic_1)) then 
                    grp_compute_greedy_potential_score_fu_288_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_pp_nn_fu_272_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_pp_nn_fu_272_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln213_1_reg_772 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_compute_pp_nn_fu_272_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_pp_nn_fu_272_ap_ready = ap_const_logic_1)) then 
                    grp_compute_pp_nn_fu_272_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    agg_result_0_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                agg_result_0_fu_86 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                agg_result_0_fu_86 <= ap_phi_mux_agg_result_3_phi_fu_195_p4;
            end if; 
        end if;
    end process;

    agg_result_2_reg_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                agg_result_2_reg_112 <= select_ln219_fu_495_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                agg_result_2_reg_112 <= agg_result_0_load_1_reg_815;
            end if; 
        end if;
    end process;

    agg_result_3_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                agg_result_3_reg_192 <= select_ln223_fu_562_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                agg_result_3_reg_192 <= agg_result_2_reg_112;
            end if; 
        end if;
    end process;

    empty_25_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                empty_25_reg_182 <= select_ln219_4_fu_536_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                empty_25_reg_182 <= empty_fu_58;
            end if; 
        end if;
    end process;

    empty_26_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                empty_26_reg_262 <= select_ln223_4_fu_617_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                empty_26_reg_262 <= empty_25_reg_182;
            end if; 
        end if;
    end process;

    empty_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                empty_fu_58 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                empty_fu_58 <= ap_phi_mux_empty_26_phi_fu_265_p4;
            end if; 
        end if;
    end process;

    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_54 <= ap_const_lv31_0;
            elsif (((icmp_ln213_1_reg_772 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_54 <= j_3_reg_762;
            end if; 
        end if;
    end process;

    j_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                j_reg_102 <= j_2_fu_625_p2;
            elsif (((icmp_ln213_fu_387_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_102 <= zext_ln213_1_fu_398_p1;
            end if; 
        end if;
    end process;

    out_r1_2_reg_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                out_r1_2_reg_132 <= select_ln219_1_fu_506_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                out_r1_2_reg_132 <= out_r1_0_load_1_reg_803;
            end if; 
        end if;
    end process;

    out_r1_3_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                out_r1_3_reg_212 <= select_ln223_1_fu_577_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                out_r1_3_reg_212 <= out_r1_2_reg_132;
            end if; 
        end if;
    end process;

    out_r2_2_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                out_r2_2_reg_152 <= select_ln219_2_fu_517_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                out_r2_2_reg_152 <= out_r2_0_load_1_reg_791;
            end if; 
        end if;
    end process;

    out_r2_3_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                out_r2_3_reg_232 <= select_ln223_2_fu_592_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                out_r2_3_reg_232 <= out_r2_2_reg_152;
            end if; 
        end if;
    end process;

    out_sign_2_reg_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                out_sign_2_reg_172 <= select_ln219_3_fu_529_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                out_sign_2_reg_172 <= out_sign_0_load_1_reg_779;
            end if; 
        end if;
    end process;

    out_sign_3_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                out_sign_3_reg_252 <= select_ln223_3_fu_608_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                out_sign_3_reg_252 <= out_sign_2_reg_172;
            end if; 
        end if;
    end process;

    write_flag3_0_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag3_0_fu_82 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                write_flag3_0_fu_82 <= ap_phi_mux_write_flag3_3_phi_fu_205_p4;
            end if; 
        end if;
    end process;

    write_flag3_2_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                write_flag3_2_reg_122 <= or_ln219_fu_501_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                write_flag3_2_reg_122 <= write_flag3_0_load_1_reg_809;
            end if; 
        end if;
    end process;

    write_flag3_3_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                write_flag3_3_reg_202 <= or_ln223_fu_570_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                write_flag3_3_reg_202 <= write_flag3_2_reg_122;
            end if; 
        end if;
    end process;

    write_flag6_0_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag6_0_fu_74 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                write_flag6_0_fu_74 <= ap_phi_mux_write_flag6_3_phi_fu_225_p4;
            end if; 
        end if;
    end process;

    write_flag6_2_reg_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                write_flag6_2_reg_142 <= or_ln219_1_fu_512_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                write_flag6_2_reg_142 <= write_flag6_0_load_1_reg_797;
            end if; 
        end if;
    end process;

    write_flag6_3_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                write_flag6_3_reg_222 <= or_ln223_1_fu_585_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                write_flag6_3_reg_222 <= write_flag6_2_reg_142;
            end if; 
        end if;
    end process;

    write_flag9_0_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag9_0_fu_66 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                write_flag9_0_fu_66 <= ap_phi_mux_write_flag9_3_phi_fu_245_p4;
            end if; 
        end if;
    end process;

    write_flag9_2_reg_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln217_reg_832 = ap_const_lv1_1))) then 
                write_flag9_2_reg_162 <= or_ln219_2_fu_524_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then 
                write_flag9_2_reg_162 <= write_flag9_0_load_1_reg_785;
            end if; 
        end if;
    end process;

    write_flag9_3_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
                write_flag9_3_reg_242 <= or_ln223_2_fu_601_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then 
                write_flag9_3_reg_242 <= write_flag9_2_reg_162;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                R_reg_741 <= R_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                agg_result_0_load_1_reg_815 <= agg_result_0_fu_86;
                out_r1_0_load_1_reg_803 <= out_r1_0_fu_78;
                out_r2_0_load_1_reg_791 <= out_r2_0_fu_70;
                out_sign_0_load_1_reg_779 <= out_sign_0_fu_62;
                trunc_ln213_reg_821 <= trunc_ln213_fu_458_p1;
                write_flag3_0_load_1_reg_809 <= write_flag3_0_fu_82;
                write_flag6_0_load_1_reg_797 <= write_flag6_0_fu_74;
                write_flag9_0_load_1_reg_785 <= write_flag9_0_fu_66;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                best_score_1_reg_887 <= grp_compute_greedy_potential_score_fu_288_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                best_score_reg_836 <= grp_compute_greedy_potential_score_fu_288_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_747 <= i_fu_54;
                j_3_reg_762 <= j_3_fu_392_p2;
                    zext_ln213_reg_753(30 downto 0) <= zext_ln213_fu_383_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln213_1_reg_772 <= icmp_ln213_1_fu_450_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                icmp_ln217_reg_832 <= icmp_ln217_fu_485_p2;
                n_reg_827 <= grp_compute_pp_nn_fu_272_ap_return_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                icmp_ln221_reg_883 <= icmp_ln221_fu_551_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                out_r1_0_fu_78 <= ap_phi_mux_out_r1_3_phi_fu_215_p4;
                out_r2_0_fu_70 <= ap_phi_mux_out_r2_3_phi_fu_235_p4;
                out_sign_0_fu_62 <= ap_phi_mux_out_sign_3_phi_fu_255_p4;
            end if;
        end if;
    end process;
    zext_ln213_reg_753(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln213_1_reg_772, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln217_fu_485_p2, ap_CS_fsm_state7, icmp_ln221_reg_883, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_ap_done, grp_compute_greedy_potential_score_fu_288_ap_done, icmp_ln213_fu_387_p2, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln213_fu_387_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln213_1_reg_772 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_1) and (icmp_ln217_fu_485_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_compute_greedy_potential_score_fu_288_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln221_reg_883 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_compute_greedy_potential_score_fu_288_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;

    M_e_0_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_0_address0, grp_compute_greedy_potential_score_fu_288_M_e_0_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_0_address0 <= grp_compute_greedy_potential_score_fu_288_M_e_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_0_address0 <= grp_compute_pp_nn_fu_272_M_e_0_address0;
        else 
            M_e_0_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    M_e_0_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_0_ce0, grp_compute_greedy_potential_score_fu_288_M_e_0_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_0_ce0 <= grp_compute_greedy_potential_score_fu_288_M_e_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_0_ce0 <= grp_compute_pp_nn_fu_272_M_e_0_ce0;
        else 
            M_e_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    M_e_0_d0 <= grp_compute_greedy_potential_score_fu_288_M_e_0_d0;

    M_e_0_we0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_e_0_we0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_0_we0 <= grp_compute_greedy_potential_score_fu_288_M_e_0_we0;
        else 
            M_e_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    M_e_1_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_1_address0, grp_compute_greedy_potential_score_fu_288_M_e_1_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_1_address0 <= grp_compute_greedy_potential_score_fu_288_M_e_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_1_address0 <= grp_compute_pp_nn_fu_272_M_e_1_address0;
        else 
            M_e_1_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    M_e_1_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_1_ce0, grp_compute_greedy_potential_score_fu_288_M_e_1_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_1_ce0 <= grp_compute_greedy_potential_score_fu_288_M_e_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_1_ce0 <= grp_compute_pp_nn_fu_272_M_e_1_ce0;
        else 
            M_e_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    M_e_1_d0 <= grp_compute_greedy_potential_score_fu_288_M_e_1_d0;

    M_e_1_we0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_e_1_we0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_1_we0 <= grp_compute_greedy_potential_score_fu_288_M_e_1_we0;
        else 
            M_e_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    M_e_2_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_2_address0, grp_compute_greedy_potential_score_fu_288_M_e_2_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_2_address0 <= grp_compute_greedy_potential_score_fu_288_M_e_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_2_address0 <= grp_compute_pp_nn_fu_272_M_e_2_address0;
        else 
            M_e_2_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    M_e_2_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_2_ce0, grp_compute_greedy_potential_score_fu_288_M_e_2_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_2_ce0 <= grp_compute_greedy_potential_score_fu_288_M_e_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_2_ce0 <= grp_compute_pp_nn_fu_272_M_e_2_ce0;
        else 
            M_e_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    M_e_2_d0 <= grp_compute_greedy_potential_score_fu_288_M_e_2_d0;

    M_e_2_we0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_e_2_we0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_2_we0 <= grp_compute_greedy_potential_score_fu_288_M_e_2_we0;
        else 
            M_e_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    M_e_3_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_3_address0, grp_compute_greedy_potential_score_fu_288_M_e_3_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_3_address0 <= grp_compute_greedy_potential_score_fu_288_M_e_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_3_address0 <= grp_compute_pp_nn_fu_272_M_e_3_address0;
        else 
            M_e_3_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    M_e_3_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_pp_nn_fu_272_M_e_3_ce0, grp_compute_greedy_potential_score_fu_288_M_e_3_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_3_ce0 <= grp_compute_greedy_potential_score_fu_288_M_e_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            M_e_3_ce0 <= grp_compute_pp_nn_fu_272_M_e_3_ce0;
        else 
            M_e_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    M_e_3_d0 <= grp_compute_greedy_potential_score_fu_288_M_e_3_d0;

    M_e_3_we0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_e_3_we0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_e_3_we0 <= grp_compute_greedy_potential_score_fu_288_M_e_3_we0;
        else 
            M_e_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    M_t_o_assign_proc : process(M_t_i, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_t_o, grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld)
    begin
        if ((((grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            M_t_o <= grp_compute_greedy_potential_score_fu_288_M_t_o;
        else 
            M_t_o <= M_t_i;
        end if; 
    end process;


    M_t_o_ap_vld_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            M_t_o_ap_vld <= grp_compute_greedy_potential_score_fu_288_M_t_o_ap_vld;
        else 
            M_t_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    R_fu_344_p2 <= std_logic_vector(unsigned(M_t_i) + unsigned(M_rows));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_compute_greedy_potential_score_fu_288_ap_done)
    begin
        if ((grp_compute_greedy_potential_score_fu_288_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_compute_pp_nn_fu_272_ap_done)
    begin
        if ((grp_compute_pp_nn_fu_272_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_compute_greedy_potential_score_fu_288_ap_done)
    begin
        if ((grp_compute_greedy_potential_score_fu_288_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln213_fu_387_p2)
    begin
        if ((((icmp_ln213_fu_387_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_agg_result_3_phi_fu_195_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, agg_result_3_reg_192, select_ln223_fu_562_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_agg_result_3_phi_fu_195_p4 <= select_ln223_fu_562_p3;
        else 
            ap_phi_mux_agg_result_3_phi_fu_195_p4 <= agg_result_3_reg_192;
        end if; 
    end process;


    ap_phi_mux_empty_26_phi_fu_265_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, empty_26_reg_262, select_ln223_4_fu_617_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_26_phi_fu_265_p4 <= select_ln223_4_fu_617_p3;
        else 
            ap_phi_mux_empty_26_phi_fu_265_p4 <= empty_26_reg_262;
        end if; 
    end process;


    ap_phi_mux_out_r1_3_phi_fu_215_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, out_r1_3_reg_212, select_ln223_1_fu_577_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_out_r1_3_phi_fu_215_p4 <= select_ln223_1_fu_577_p3;
        else 
            ap_phi_mux_out_r1_3_phi_fu_215_p4 <= out_r1_3_reg_212;
        end if; 
    end process;


    ap_phi_mux_out_r2_3_phi_fu_235_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, out_r2_3_reg_232, select_ln223_2_fu_592_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_out_r2_3_phi_fu_235_p4 <= select_ln223_2_fu_592_p3;
        else 
            ap_phi_mux_out_r2_3_phi_fu_235_p4 <= out_r2_3_reg_232;
        end if; 
    end process;


    ap_phi_mux_out_sign_3_phi_fu_255_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, out_sign_3_reg_252, select_ln223_3_fu_608_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_out_sign_3_phi_fu_255_p4 <= select_ln223_3_fu_608_p3;
        else 
            ap_phi_mux_out_sign_3_phi_fu_255_p4 <= out_sign_3_reg_252;
        end if; 
    end process;


    ap_phi_mux_write_flag3_3_phi_fu_205_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, write_flag3_3_reg_202, or_ln223_fu_570_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_write_flag3_3_phi_fu_205_p4 <= or_ln223_fu_570_p2;
        else 
            ap_phi_mux_write_flag3_3_phi_fu_205_p4 <= write_flag3_3_reg_202;
        end if; 
    end process;


    ap_phi_mux_write_flag6_3_phi_fu_225_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, write_flag6_3_reg_222, or_ln223_1_fu_585_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_write_flag6_3_phi_fu_225_p4 <= or_ln223_1_fu_585_p2;
        else 
            ap_phi_mux_write_flag6_3_phi_fu_225_p4 <= write_flag6_3_reg_222;
        end if; 
    end process;


    ap_phi_mux_write_flag9_3_phi_fu_245_p4_assign_proc : process(icmp_ln221_reg_883, ap_CS_fsm_state11, write_flag9_3_reg_242, or_ln223_2_fu_601_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln221_reg_883 = ap_const_lv1_1))) then 
            ap_phi_mux_write_flag9_3_phi_fu_245_p4 <= or_ln223_2_fu_601_p2;
        else 
            ap_phi_mux_write_flag9_3_phi_fu_245_p4 <= write_flag9_3_reg_242;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln213_fu_387_p2)
    begin
        if (((icmp_ln213_fu_387_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= agg_result_0_fu_86;
    ap_return_1 <= select_ln228_fu_402_p3;
    ap_return_2 <= select_ln228_1_fu_410_p3;
    ap_return_3 <= select_ln228_2_fu_418_p3;
    grp_compute_greedy_potential_score_fu_288_ap_start <= grp_compute_greedy_potential_score_fu_288_ap_start_reg;

    grp_compute_greedy_potential_score_fu_288_sign_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_compute_greedy_potential_score_fu_288_sign <= ap_const_lv2_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_compute_greedy_potential_score_fu_288_sign <= ap_const_lv2_1;
        else 
            grp_compute_greedy_potential_score_fu_288_sign <= "XX";
        end if; 
    end process;

    grp_compute_pp_nn_fu_272_ap_start <= grp_compute_pp_nn_fu_272_ap_start_reg;
    icmp_ln213_1_fu_450_p2 <= "1" when (j_reg_102 = R_reg_741) else "0";
    icmp_ln213_fu_387_p2 <= "1" when (signed(zext_ln213_fu_383_p1) < signed(R_reg_741)) else "0";
    icmp_ln217_fu_485_p2 <= "1" when (signed(tmp_fu_475_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln219_fu_491_p2 <= "1" when (signed(best_score_reg_836) > signed(empty_fu_58)) else "0";
    icmp_ln221_fu_551_p2 <= "1" when (signed(tmp_4_fu_542_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln223_fu_557_p2 <= "1" when (signed(best_score_1_reg_887) > signed(empty_25_reg_182)) else "0";
    j_2_fu_625_p2 <= std_logic_vector(unsigned(j_reg_102) + unsigned(ap_const_lv32_1));
    j_3_fu_392_p2 <= std_logic_vector(unsigned(i_fu_54) + unsigned(ap_const_lv31_1));
    or_ln219_1_fu_512_p2 <= (write_flag6_0_load_1_reg_797 or icmp_ln219_fu_491_p2);
    or_ln219_2_fu_524_p2 <= (write_flag9_0_load_1_reg_785 or icmp_ln219_fu_491_p2);
    or_ln219_fu_501_p2 <= (write_flag3_0_load_1_reg_809 or icmp_ln219_fu_491_p2);
    or_ln223_1_fu_585_p2 <= (write_flag6_2_reg_142 or icmp_ln223_fu_557_p2);
    or_ln223_2_fu_601_p2 <= (write_flag9_2_reg_162 or icmp_ln223_fu_557_p2);
    or_ln223_fu_570_p2 <= (write_flag3_2_reg_122 or icmp_ln223_fu_557_p2);
    select_ln219_1_fu_506_p3 <= 
        zext_ln213_reg_753 when (icmp_ln219_fu_491_p2(0) = '1') else 
        out_r1_0_load_1_reg_803;
    select_ln219_2_fu_517_p3 <= 
        j_reg_102 when (icmp_ln219_fu_491_p2(0) = '1') else 
        out_r2_0_load_1_reg_791;
    select_ln219_3_fu_529_p3 <= 
        ap_const_lv32_1 when (icmp_ln219_fu_491_p2(0) = '1') else 
        out_sign_0_load_1_reg_779;
    select_ln219_4_fu_536_p3 <= 
        best_score_reg_836 when (icmp_ln219_fu_491_p2(0) = '1') else 
        empty_fu_58;
    select_ln219_fu_495_p3 <= 
        best_score_reg_836 when (icmp_ln219_fu_491_p2(0) = '1') else 
        agg_result_0_load_1_reg_815;
    select_ln223_1_fu_577_p3 <= 
        zext_ln213_reg_753 when (icmp_ln223_fu_557_p2(0) = '1') else 
        out_r1_2_reg_132;
    select_ln223_2_fu_592_p3 <= 
        j_reg_102 when (icmp_ln223_fu_557_p2(0) = '1') else 
        out_r2_2_reg_152;
    select_ln223_3_fu_608_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln223_fu_557_p2(0) = '1') else 
        out_sign_2_reg_172;
    select_ln223_4_fu_617_p3 <= 
        best_score_1_reg_887 when (icmp_ln223_fu_557_p2(0) = '1') else 
        empty_25_reg_182;
    select_ln223_fu_562_p3 <= 
        best_score_1_reg_887 when (icmp_ln223_fu_557_p2(0) = '1') else 
        agg_result_2_reg_112;
    select_ln228_1_fu_410_p3 <= 
        out_r2_0_fu_70 when (write_flag6_0_fu_74(0) = '1') else 
        ap_const_lv32_0;
    select_ln228_2_fu_418_p3 <= 
        out_sign_0_fu_62 when (write_flag9_0_fu_66(0) = '1') else 
        ap_const_lv32_0;
    select_ln228_fu_402_p3 <= 
        out_r1_0_fu_78 when (write_flag3_0_fu_82(0) = '1') else 
        ap_const_lv32_0;
    tmp_4_fu_542_p4 <= n_reg_827(31 downto 1);
    tmp_fu_475_p4 <= grp_compute_pp_nn_fu_272_ap_return_0(31 downto 1);
    trunc_ln213_fu_458_p1 <= j_reg_102(9 - 1 downto 0);
    zext_ln213_1_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_3_fu_392_p2),32));
    zext_ln213_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_54),32));
end behav;
