// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cols_non_t,
        mul_ln118,
        M_e_address0,
        M_e_ce0,
        M_e_q0,
        M_e_address1,
        M_e_ce1,
        M_e_q1,
        j_1,
        n_out,
        n_out_ap_vld,
        p_out,
        p_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] cols_non_t;
input  [16:0] mul_ln118;
output  [16:0] M_e_address0;
output   M_e_ce0;
input  [31:0] M_e_q0;
output  [16:0] M_e_address1;
output   M_e_ce1;
input  [31:0] M_e_q1;
input  [16:0] j_1;
output  [31:0] n_out;
output   n_out_ap_vld;
output  [31:0] p_out;
output   p_out_ap_vld;

reg ap_idle;
reg n_out_ap_vld;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln116_fu_135_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln116_reg_337;
wire   [16:0] add_ln118_fu_151_p2;
reg   [16:0] add_ln118_reg_341;
reg  signed [31:0] e2_reg_356;
wire   [63:0] zext_ln120_fu_181_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln118_fu_191_p1;
reg   [31:0] p_fu_44;
wire   [31:0] p_3_fu_274_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [31:0] n_fu_48;
wire   [31:0] n_2_fu_288_p3;
reg   [30:0] c_fu_52;
wire   [30:0] add_ln116_fu_141_p2;
reg   [30:0] ap_sig_allocacmp_c_8;
wire    ap_block_pp0_stage0_01001;
reg    M_e_ce1_local;
reg    M_e_ce0_local;
wire   [31:0] zext_ln116_fu_131_p1;
wire   [16:0] trunc_ln118_fu_147_p1;
wire   [16:0] shl_ln120_fu_157_p2;
wire   [16:0] shl_ln120_3_fu_163_p2;
wire   [16:0] add_ln120_4_fu_169_p2;
wire   [16:0] add_ln120_fu_175_p2;
wire  signed [31:0] icmp_ln119_fu_201_p0;
wire  signed [31:0] icmp_ln122_fu_212_p0;
wire  signed [32:0] sext_ln123_fu_223_p1;
wire  signed [31:0] sext_ln123_1_fu_232_p0;
wire  signed [32:0] sext_ln123_1_fu_232_p1;
wire   [32:0] sub_ln123_fu_226_p2;
wire   [0:0] icmp_ln123_fu_236_p2;
wire   [31:0] add_ln123_fu_242_p2;
wire   [0:0] icmp_ln119_fu_201_p2;
wire   [0:0] icmp_ln121_fu_207_p2;
wire   [0:0] icmp_ln122_fu_212_p2;
wire   [0:0] or_ln121_fu_256_p2;
wire   [0:0] xor_ln122_fu_262_p2;
wire   [0:0] or_ln122_fu_268_p2;
wire   [31:0] p_7_fu_217_p2;
wire   [0:0] or_ln122_1_fu_282_p2;
wire   [31:0] n_8_fu_248_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 p_fu_44 = 32'd0;
#0 n_fu_48 = 32'd0;
#0 c_fu_52 = 31'd0;
#0 ap_done_reg = 1'b0;
end

fmm_reduce_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln116_fu_135_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_52 <= add_ln116_fu_141_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_52 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            n_fu_48 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            n_fu_48 <= n_2_fu_288_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            p_fu_44 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            p_fu_44 <= p_3_fu_274_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln118_reg_341 <= add_ln118_fu_151_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln116_reg_337 <= icmp_ln116_fu_135_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e2_reg_356 <= M_e_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_ce0_local = 1'b1;
    end else begin
        M_e_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M_e_ce1_local = 1'b1;
    end else begin
        M_e_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_135_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_8 = 31'd0;
    end else begin
        ap_sig_allocacmp_c_8 = c_fu_52;
    end
end

always @ (*) begin
    if (((icmp_ln116_reg_337 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        n_out_ap_vld = 1'b1;
    end else begin
        n_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_reg_337 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_e_address0 = zext_ln118_fu_191_p1;

assign M_e_address1 = zext_ln120_fu_181_p1;

assign M_e_ce0 = M_e_ce0_local;

assign M_e_ce1 = M_e_ce1_local;

assign add_ln116_fu_141_p2 = (ap_sig_allocacmp_c_8 + 31'd1);

assign add_ln118_fu_151_p2 = (mul_ln118 + trunc_ln118_fu_147_p1);

assign add_ln120_4_fu_169_p2 = (shl_ln120_fu_157_p2 + shl_ln120_3_fu_163_p2);

assign add_ln120_fu_175_p2 = (add_ln120_4_fu_169_p2 + trunc_ln118_fu_147_p1);

assign add_ln123_fu_242_p2 = (n_fu_48 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln116_fu_135_p2 = (($signed(zext_ln116_fu_131_p1) < $signed(cols_non_t)) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_201_p0 = M_e_q0;

assign icmp_ln119_fu_201_p2 = ((icmp_ln119_fu_201_p0 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_207_p2 = ((e2_reg_356 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_212_p0 = M_e_q0;

assign icmp_ln122_fu_212_p2 = ((icmp_ln122_fu_212_p0 == e2_reg_356) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_236_p2 = ((sext_ln123_1_fu_232_p1 == sub_ln123_fu_226_p2) ? 1'b1 : 1'b0);

assign n_2_fu_288_p3 = ((or_ln122_1_fu_282_p2[0:0] == 1'b1) ? n_fu_48 : n_8_fu_248_p3);

assign n_8_fu_248_p3 = ((icmp_ln123_fu_236_p2[0:0] == 1'b1) ? add_ln123_fu_242_p2 : n_fu_48);

assign n_out = n_fu_48;

assign or_ln121_fu_256_p2 = (icmp_ln121_fu_207_p2 | icmp_ln119_fu_201_p2);

assign or_ln122_1_fu_282_p2 = (or_ln121_fu_256_p2 | icmp_ln122_fu_212_p2);

assign or_ln122_fu_268_p2 = (xor_ln122_fu_262_p2 | or_ln121_fu_256_p2);

assign p_3_fu_274_p3 = ((or_ln122_fu_268_p2[0:0] == 1'b1) ? p_fu_44 : p_7_fu_217_p2);

assign p_7_fu_217_p2 = (p_fu_44 + 32'd1);

assign p_out = p_fu_44;

assign sext_ln123_1_fu_232_p0 = M_e_q0;

assign sext_ln123_1_fu_232_p1 = sext_ln123_1_fu_232_p0;

assign sext_ln123_fu_223_p1 = e2_reg_356;

assign shl_ln120_3_fu_163_p2 = j_1 << 17'd6;

assign shl_ln120_fu_157_p2 = j_1 << 17'd8;

assign sub_ln123_fu_226_p2 = ($signed(33'd0) - $signed(sext_ln123_fu_223_p1));

assign trunc_ln118_fu_147_p1 = ap_sig_allocacmp_c_8[16:0];

assign xor_ln122_fu_262_p2 = (icmp_ln122_fu_212_p2 ^ 1'd1);

assign zext_ln116_fu_131_p1 = ap_sig_allocacmp_c_8;

assign zext_ln118_fu_191_p1 = add_ln118_reg_341;

assign zext_ln120_fu_181_p1 = add_ln120_fu_175_p2;

endmodule //fmm_reduce_kernel_greedy_potential_reduce_with_debug_Pipeline_VITIS_LOOP_116_1
